export type Facility = {
  id: string;
  name: string;
  nameHira?: string;
  description: string;
  fullDescription?: string;
  address: string;
  facilityDescription: string;
  parking?: string;
  fee?: string;
  remarks?: string;
  facilityList: {
    area?: string;
    description?: string;
    imgPath?: string;
  }[];
  access: string;
  caseCategory?: string;
  caseId?: string;
  imagePath?: string;
  hasMorgue?: boolean;
  ceremore?: boolean;
  ceremoreFullLogo?: string;
};

export const SHIKIJIOU: Facility[] = [{
  id: '1',
  name: '増上寺',
  nameHira: 'ぞうじょうじ',
  description: '徳川将軍家とのゆかりの深い浄土宗の大本山である増上寺には、大殿（本堂）、光摂殿、慈雲閣と3つの式場があり、葬儀の規模により選択できます。知名度、交通の利便性も高く、多くの格式高い葬儀に利用されています。',
  fullDescription: '日本でも有数な大寺院として発展した増上寺は、重要文化財、東京都指定有形文化財を多く保有し、知名度も高く、立地的に東京タワーの真下（真南）であると案内しやすく、格式高いお葬儀に多く利用されています。光摂殿は、屋根のある踊り場（ピロティ）があり、受付スペースとして利用可能です。会葬者が1,000人を超す場合は、敷地スペースに大型テントを配置することにより、対応できます。控室部屋数も多く、会葬者のお待ちいただくスペースやお清めの席を確保することができます。一般の方の参拝もあり、駐車場は特別な駐車体制をとるため、葬儀専用の警備員を配置する必要があります。',
  address: '東京都港区芝公園4-7-35',
  facilityDescription: '光摂殿：250席　大殿：500席　慈雲閣：100席',
  parking: '100台',
  fee: '式場使用料：「大殿」400万、「光摂殿」100万、「慈雲閣」60万',
  remarks: '仏式のみ利用可。<br>日蓮宗、新興宗教、キリスト、神道は不可。',
  facilityList: [{
    area: '門',
    description: '',
    imgPath: '/images/sougijou/01/1_1.jpg',
  }, {
    area: '本堂（大殿）',
    description: '',
    imgPath: '/images/sougijou/01/1_2.jpg',
  }, {
    area: '本堂（大殿）入口',
    description: '',
    imgPath: '/images/sougijou/01/1_3.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/01/1_4.jpg',
  }, {
    area: '式場（光摂殿）',
    description: '',
    imgPath: '/images/sougijou/01/1_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/01/1_6.jpg',
  }],
  access: '都営三田線「御成門駅」または「芝公園駅」より共に徒歩3分。<br />都営浅草線・大江戸線「大門駅」より徒歩5分。<br />JR山手線・京浜東北線・東京モノレール「浜松町駅」より徒歩10分。',
  caseCategory: 'syasou',
  caseId: '001',
  imagePath: '/images/sougijou/01/1_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '2',
  name: '寛永寺',
  nameHira: 'かんえいじ',
  description: '寛永寺（輪王殿）は、東京都台東区にある寺院が運営する葬儀式場です。戦争時の弾痕が多数残る黒門に守られた、天台宗関東総本山の寺院です。徳川将軍家の菩提寺であり、徳川の歴代将軍15人中6人が寛永寺に眠っています。上野駅からの道程もわかりやすく、多くの弔問客にも対応することができます。式場内は、正面からの動線が作りやすく、スムーズな式の進行ができます。',
  fullDescription: '上野駅公園口から右、公園・国立科学博物館をすぎると有名な黒門が見えてきます。第一会場が正面にあり、裏側に第二会場があります。全館での使用も可能です。第二会場では、少人数でのご利用も可能です。 規模により、室内受付も可能であり、会葬者数が大勢と予想される場合は、敷地スペースにテントを配置することにより、祭壇まで直線的に動線を確保でき、スムーズな式の進行ができます。 寺院内の施設のため、お寺様の行事等で使用できない場合もあります。また通夜での宿泊はできないので、近くのホテルをご紹介しています。',
  address: '東京都台東区上野公園14-5',
  facilityDescription: '第1会場：200席　第2会場：80席',
  parking: '70台',
  fee: '輪王殿第一式場：式場使用料：1,350,000円～<br>輪王殿第二式場：式場使用料：650,000円～',
  remarks: '仏教徒であれば宗派制限なし、新興宗教・キリスト教は要問合せ',
  facilityList: [{
    area: '門',
    description: '',
    imgPath: '/images/sougijou/02/2_1.jpg',
  }, {
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/02/2_2.jpg',
  }, {
    area: 'ロビー（第一式場）',
    description: '',
    imgPath: '/images/sougijou/02/2_3.jpg',
  }, {
    area: 'ロビー（第一式場）2',
    description: '',
    imgPath: '/images/sougijou/02/2_4.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/02/2_5.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/02/2_6.jpg',
  }],
  access: 'JR山手線・京浜東北線「上野駅」公園口、または「鶯谷駅」南口より共に徒歩5分。',
  caseCategory: 'syasou',
  caseId: '003',
  imagePath: '/images/sougijou/02/2_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '3',
  name: '護国寺',
  nameHira: 'ごこくじ',
  description: '真言宗、豊山派の大本山として格式高く、徳川綱吉の母、桂昌院の発願により建てられたお寺です。大規模葬儀に適した式場で、葬儀の規模により、敷地内に自在にテントを配置することが可能。大規模式場の中で、もっとも駅から近く交通の便に優れています。',
  fullDescription: '多くの文化財を有する護国寺は、重要文化財の観音堂（本堂）、近江三井寺から移築された月光殿（重文）は、創建当時の建築美を今に伝えております。また大隈重信ら多くの著名人の墓所としても知られています。緑も豊富で環境が良く、式場までのスペースを充分に確保でき、テント配置が可能で、多くの会葬者にも対応できます。 悪天候の場合でも、室内に受付を配置したり、式場前スペースで、受付・通路・待合所のテント配置も可能です。寺院内の施設のため、お寺様の行事等で使用できない場合もあります。また通夜での宿泊はできないので、近くのホテルをご紹介しています',
  address: '東京都文京区大塚5-40-1',
  facilityDescription: '160席',
  parking: '80台',
  fee: '式場使用料：80万円　通・告・初七日',
  remarks: '仏式・神式のみ利用可、無宗教・音楽葬は不可。',
  facilityList: [{
    area: '門',
    description: '',
    imgPath: '/images/sougijou/03/3_1.jpg',
  }, {
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/03/3_2.jpg',
  }, {
    area: '玄関口',
    description: '',
    imgPath: '/images/sougijou/03/3_3.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/03/3_4.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/03/3_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/03/3_6.jpg',
  }],
  access: '東京メトロ有楽町線　「護国寺駅」より徒歩すぐ。',
  caseCategory: 'goudousou',
  caseId: '002',
  imagePath: '/images/sougijou/03/3_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '4',
  name: '築地本願寺',
  nameHira: 'つきじほんがんじ',
  description: '「築地本願寺」と略称で親しまれているこのお寺は、正式には「浄土真宗本願寺派本願寺築地別院」と言います。本堂・第二伝道会館の2会場で、第二伝道会館は「蓮華殿」と「瑞鳳の間」の式場があり、3つの式場から選択することができます。',
  fullDescription: '古代インド様式の本堂は500席と首都圏最大級の式場で、第二伝道会館「蓮華殿」が200席、「瑞鳳の間」100席と規模により選択して利用する事ができます。本堂を利用する葬儀では会葬者1,000人以上の葬儀になり、大型テントを敷地に配置することができます。第二伝道会館はロビーが広く、場内スペースが充分にあるので、悪天候でも式場内で、会葬者の皆様がお待ちいただくことができます。',
  address: '東京都中央区築地3-15-1',
  facilityDescription: '本堂：500席　第2伝道会館：180席',
  parking: '50台',
  fee: '本堂：式場使用料：4,000,000円仏式なら可　但し日蓮正宗は不可<br>第二伝道会館：式場使用料：800,000円',
  remarks: '仏式のみ利用可、日蓮正宗は不可。',
  facilityList: [{
    area: '本堂　入口',
    description: '',
    imgPath: '/images/sougijou/04/4_1.jpg',
  }, {
    area: '本堂内',
    description: '',
    imgPath: '/images/sougijou/04/4_2.jpg',
  }, {
    area: '式場（第二伝道会館）外観',
    description: '',
    imgPath: '/images/sougijou/04/4_3.jpg',
  }, {
    area: '式場（第二伝道会館）',
    description: '',
    imgPath: '/images/sougijou/04/4_4.jpg',
  }, {
    area: '式場（第二伝道会館）ロビー',
    description: '',
    imgPath: '/images/sougijou/04/4_5.jpg',
  }, {
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/04/4_6.jpg',
  }],
  access: '東京メトロ日比谷線「築地駅」本願寺前出口より徒歩2分。',
  caseCategory: 'goudousou',
  caseId: '001',
  imagePath: '/images/sougijou/04/4_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '5',
  name: '宝仙寺',
  nameHira: 'ほうせんじ',
  description: '宝仙寺は真言宗豊山派の寺院です。 中野・杉並の近郊で大きな葬儀といえば宝仙寺と言われるほど、有名なお寺です。 大師堂は著名人が数多く葬儀を執り行われることでも有名な、格式ある式場です。本堂は檀家のみ使用可です。',
  fullDescription: '仁王様が納められた山門（仁王門）をくぐると、正面に本堂、右手に大師堂があります。広大な敷地スペースは車で来られた方が有効にご利用いただけます。 全館使用をすることで、会葬者の待合所、係員の控室、お清めの席数確保ができ、室内で会葬者をお迎えすることが可能です。会葬者が大勢と予想される場合は、式場前の敷地スペースにテントを配置し、受付・待機・クローク、お清めなどを大きく作ることができるため、1,000人規模の会葬者にも対応できます。',
  address: '東京都中野区中央2-33-3',
  facilityDescription: '第一：150席　第二：40席',
  parking: '約50台',
  fee: '式場使用料：全館使用で700,000円～',
  remarks: '仏式、神式のみ利用可。',
  facilityList: [{
    area: '門',
    description: '',
    imgPath: '/images/sougijou/05/5_1.jpg',
  }, {
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/05/5_2.jpg',
  }, {
    area: '大師堂',
    description: '',
    imgPath: '/images/sougijou/05/5_3.jpg',
  }, {
    area: '式場入口',
    description: '',
    imgPath: '/images/sougijou/05/5_4.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/05/5_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/05/5_6.jpg',
  }],
  access: '東京メト丸の内線・都営大江戸線「中野坂上駅」より徒歩6分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/05/5_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '6',
  name: 'セレモア立川会館 白峯殿',
  nameHira: 'せれもあたちかわかいかん はくほうでん',
  description: 'セレモア立川会館 白峯殿は昭和記念公園の東、すずかけ通りに面した多摩エリア最大の葬儀式場です。家族葬や一般葬から2,000名規模の社葬・お別れの会・合同葬まで、あらゆるお葬儀に対応可能な、大規模葬儀式場です。',
  fullDescription: '緑に囲まれた落ち着いた雰囲気の中で、ご家族だけの密葬から社葬・お別れの会・合同葬・追悼コンサートまで、幅広くご法事やお葬儀に対応できる式場です。 広く、ゆったりとした第一式場には世界三大名器「ベーゼンドルファー」を常設しており、お式に際し自由にご利用いただけます。第一式場、第二式場の全館利用においては、2,000名規模ので大規模な社葬・お別れの会に対応しております。最新の音響、照明、映像設備にもこだわり、儀式を厳粛に演出いたします。',
  address: '東京都立川市柏町1-26-4',
  facilityDescription: '第一式場：180席　第二式場：24席　第一式場、第二式場の全館使用も承ります。',
  parking: '180台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/06/6_1.jpg',
  }, {
    area: 'お清め所',
    description: '',
    imgPath: '/images/sougijou/06/6_2.jpg',
  }, {
    area: '遺族控室',
    description: '',
    imgPath: '/images/sougijou/06/6_3.jpg',
  }, {
    area: '来賓控室',
    description: '',
    imgPath: '/images/sougijou/06/6_4.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/06/6_5.jpg',
  }, {
    area: '受付室',
    description: '',
    imgPath: '/images/sougijou/06/6_6.jpg',
  }],
  access: 'JR中央線「立川駅」北口下車、多摩モノレール「立川北駅」より「上北台駅」行き乗車。<br /><br />「泉体育館」下車、すずかけ通り「幸町１丁目」交差点から西へ徒歩約8分。<br /><br />西武拝島線「玉川上水駅」下車、多摩モノレール「玉川上水駅」より「多摩センター駅」行き乗車。<br /><br />「泉体育館駅」下車、すずかけ通り「幸町１丁目」交差点から西へ徒歩約8分。',
  caseCategory: 'goudousou',
  caseId: '003',
  imagePath: '/images/sougijou/06/6_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/06/tachikawa_hakuho.png',
},
{
  id: '7',
  name: '桐ヶ谷斎場',
  nameHira: 'きりがやさいじょう',
  description: '桐ヶ谷斎場は火葬場併設の式場です。12の火葬炉、6つの式場があり、家族葬から大規模な葬儀まで対応が可能です。ご遺体のお預かり、お通夜から告別式、精進落としまで、お葬儀全般を行える葬儀式場です。',
  fullDescription: '葬儀式場と火葬場が併設された民間の施設です。最寄り駅からのアクセスは、東急目黒線「不動前駅」より徒歩7分です。式場の客席は40席・80席・160席で、家族葬から一般葬・社葬まで規模に応じたお葬儀に対応できる式場です。駐車場は94台までご利用いただけます。一番大きな「雲の間」では、格式ある社葬を執り行うことができます。',
  address: '東京都品川区西五反田5-32-20',
  facilityDescription: '雲の間：160席　鶴の間：80席　雪の間：40席',
  parking: '駐車場有り',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/07/7_1.jpg',
  }, {
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/07/7_2.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/07/7_3.jpg',
  }, {
    area: '控室',
    description: '',
    imgPath: '/images/sougijou/07/7_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/07/7_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/07/7_6.jpg',
  }],
  access: 'JR山手線・都営浅草線「五反田駅」西口より東急バス「五反田~渋谷」乗車、「桐ヶ谷」下車すぐ。<br /><br />東急目黒線「不動前駅」より徒歩7分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/07/7_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '8',
  name: '高野山東京別院',
  nameHira: 'こうやさんとうきょうべついん',
  description: '高野山東京別院は、東京都港区高輪にある寺院が運営する葬儀式場です。',
  fullDescription: '高野山真言宗 総本山金剛峯寺の別院です。 慶長年間、高野山の宝門・寿門の学侶方の在番所として開創され、延宝元年(1673年)「高野山江戸在番所高野寺」として建立されました。1927年に「高野山東京別院」と改称し、1988年には現在の本堂が建立され、首都圏における「大師信仰」の教化の拠点となっています。 最寄り駅からのアクセスは、都営浅草線「高輪台駅」より徒歩6分です。式場の客席は本堂が150席、斎場が70席で、家族葬からご会葬のある葬儀まで規模に応じたお葬儀に対応できる式場です。駐車場は60台までご利用いただけます。',
  address: '東京都港区高輪3-15-18',
  facilityDescription: '本堂：150席　斎場：70席',
  parking: '60台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/08/8_1.jpg',
  }, {
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/08/8_2.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/08/8_3.jpg',
  }, {
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/08/8_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/08/8_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/08/8_6.jpg',
  }],
  access: '都営浅草線「高輪台駅」より徒歩6分。<br />東京メトロ南北線・都営三田線「白金台駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/08/8_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '9',
  name: '梅窓院',
  nameHira: 'ばいそういん',
  description: '浄土宗梅窓院は、世界的な建築家・隈研吾氏が都市の中にオアシスのようなお寺をデザインしたお寺です。',
  fullDescription: '東京メトロ銀座線「外苑前駅」より徒歩2分の好条件のお寺です。家族葬からご会葬のある葬儀まで規模に応じたお葬儀に対応できる式場です。駐車場は20台までご利用いただけます。',
  address: '東京都港区南青山2-26-38',
  facilityDescription: '60席',
  parking: '20台',
  fee: '式場使用料：340,000円　（通・告・初七日）<br>※観音堂を使用した場合',
  remarks: '在来仏教以外は不可',
  facilityList: [{
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/09/9_1.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/09/9_2.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/09/9_3.jpg',
  }, {
    area: '参道',
    description: '',
    imgPath: '/images/sougijou/09/9_4.jpg',
  }, {
    area: '門',
    description: '',
    imgPath: '/images/sougijou/09/9_5.jpg',
  }, {
    area: '出棺',
    description: '',
    imgPath: '/images/sougijou/09/9_6.jpg',
  }],
  access: '東京メトロ銀座線「外苑前駅」より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/09/9_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '10',
  name: '傳通院',
  nameHira: 'でんづういん',
  description: '傳通院（繊月会館）は、東京都文京区にある寺院で慶長8年（1603）徳川家康が生母お大をこの地に葬った徳川家ゆかりのお寺です。内には、お大の方、千姫（豊臣秀頼妻・2代徳川秀忠の長女）をはじめとして徳川家ゆかりの女性の墓が数多くある。',
  fullDescription: '傳通院（繊月会館）は、多目的な檀信徒会館です。会館は地上３階地下１階建て、鉄筋コンクリート造りでエレベーターも完備されています。最寄り駅からのアクセスは、都営大江戸線・三田線「春日駅」より徒歩10分です。式場の客席は150席で、家族葬から一般葬、社葬、合同葬まで規模に応じたお葬儀に対応できる式場です。駐車場は40台までご利用いただけます。',
  address: '東京都文京区小石川 3-14-6',
  facilityDescription: '150席',
  parking: '40台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '山門',
    description: '',
    imgPath: '/images/sougijou/10/10_1.jpg',
  }, {
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/10/10_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/10/10_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/10/10_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/10/10_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/10/10_6.jpg',
  }],
  access: '都営大江戸線・三田線「春日駅」より徒歩10分。<br />東京メトロ丸の内線・南北線「後楽園駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/10/10_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '11',
  name: '落合斎場',
  nameHira: 'おちあいさいじょう',
  description: '落合斎場は、東京都新宿区にある火葬場が併設された民間の総合斎場です。式場と火葬場が併設なので、お車での移動がないので、ご負担が少なくなります。',
  fullDescription: '東京メトロ東西線「落合駅」より徒歩5分です。式場の客席は40席で、家族葬からご会葬のある葬儀まで規模に応じたお葬儀に対応できる式場です。駐車場は80台までご利用いただけます。お体のお預り・通夜・告別式・ご火葬・会食まで、儀式の全てを同じ施設内で行える総合斎場です。少人数のお葬式から、儀式はせずご火葬のみを行う葬儀、ご縁のあった皆様と共に送るお葬式まで、様々な形式に対応致します。',
  address: '東京都新宿区上落合3-34-12',
  facilityDescription: '40席',
  parking: '80台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/11/11_1.jpg',
  }, {
    area: 'ラウンジ',
    description: '',
    imgPath: '/images/sougijou/11/11_2.jpg',
  }, {
    area: '控室-1',
    description: '',
    imgPath: '/images/sougijou/11/11_3.jpg',
  }, {
    area: '控室-2',
    description: '',
    imgPath: '/images/sougijou/11/11_4.jpg',
  }, {
    area: '火葬棟　外観',
    description: '',
    imgPath: '/images/sougijou/11/11_5.jpg',
  }, {
    area: '火葬棟　ロビー',
    description: '',
    imgPath: '/images/sougijou/11/11_6.jpg',
  }],
  access: '東京メトロ東西線「落合駅」より徒歩5分。<br />都営大江戸線・西武新宿線「中井駅」より徒歩10分。<br />JR総武線「東中野駅」より徒歩15分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/11/11_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '12',
  name: '太宗寺',
  nameHira: 'たいそうじ',
  description: '太宗寺は、東京都新宿区にある浄土宗の寺院です。<br /> 最寄り駅からのアクセスは、東京メトロ丸の内線「新宿御苑前駅」より徒歩3分。都営新宿線「新宿三丁目駅」から徒歩3分です。',
  fullDescription: '最寄り駅からのアクセスは、東京メトロ丸の内線「新宿御苑前駅」より徒歩3分。都営新宿線「新宿三丁目駅」から徒歩3分です。式場の客席は100席で、家族葬から一般葬・大規模葬まで規模に応じたお葬儀に対応できる式場です。駐車場は40台までご利用いただけます。',
  address: '東京都新宿区新宿2-9-2',
  facilityDescription: '100席',
  parking: '40台',
  fee: '式場使用料：450,000円　（通・告・初七日）',
  remarks: '仏教全般・神道以外は不可',
  facilityList: [{
    area: '屋外テント',
    description: '',
    imgPath: '/images/sougijou/12/12_1.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/12/12_2.jpg',
  }, {
    area: '弔辞',
    description: '',
    imgPath: '/images/sougijou/12/12_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/12/12_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/12/12_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/12/12_6.jpg',
  }],
  access: '東京メトロ丸の内線「新宿御苑前駅」より徒歩3分。<br />都営新宿線「新宿三丁目駅」から徒歩3分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/12/12_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '69',
  name: '代々幡斎場',
  nameHira: 'よよはたさいじょう',
  description: '代々幡斎場は、東京都渋谷区にある火葬場が併設された民間の総合斎場です。式場と火葬場が併設なので、お車での移動がないので、ご負担が少なくなります。',
  fullDescription: '都心に続く緑の山の手、優雅さを兼ね備えた代々幡斎場は都内でも広く名の通った格式高い式場です。<br /> 火葬場が併設された民間の斎場で、お通夜、告別式、火葬までの全てを行うことが可能です。<br /> 家族葬から一般葬まで幅広くご利用いただけます。また2式場を1式場として利用すれば最大300名規模までの大規模な葬儀にも対応が可能です。民営のため、宗旨宗派を問わず、どなたでもご利用いただけます。<br /> 最寄りの京王線「幡ヶ谷」駅からは徒歩6分と恵まれた立地です。',
  address: '東京都渋谷区西原2-42-1',
  facilityDescription: '雪：40席　竹：10名',
  parking: '60台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/69/69_1.jpg',
  }, {
    area: '控室-1',
    description: '',
    imgPath: '/images/sougijou/69/69_2.jpg',
  }, {
    area: '控室-2',
    description: '',
    imgPath: '/images/sougijou/69/69_3.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/69/69_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/69/69_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/69/69_6.jpg',
  }],
  access: '京王新線 「幡ヶ谷駅」南口出口より徒歩6分。<br />小田急線 東京メトロ千代田線「代々木上原駅」北口1出口より徒歩20分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/69/69_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '70',
  name: '堀ノ内斎場',
  nameHira: 'ほりのうちさいじょう',
  description: '堀ノ内斎場は、東京都杉並区にある火葬場が併設された民間の総合斎場です。式場と火葬場が併設なので、お車での移動がないので、ご負担が少なくなります。',
  fullDescription: '堀ノ内斎場は、火葬場が併設された民間斎場です。<br /> 40席の式場が3つあり、家族葬から一般葬まで幅広く対応しております。全館を貸し切っての大規模葬儀にも対応が可能です。民営のため、宗旨宗派を問わず、どなたでもご利用いただけます。<br /> 火葬場併設なので、葬儀・告別式後の火葬場への移動がスムーズです。<br /> また、控室やロビー、コーヒーコーナー、売店などの設備も充実しております。',
  address: '東京都杉並区梅里1-2-27',
  facilityDescription: '雪：40席',
  parking: '20台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/70/70_1.jpg',
  }, {
    area: '式場控室',
    description: '',
    imgPath: '/images/sougijou/70/70_2.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/70/70_3.jpg',
  }, {
    area: '休憩室',
    description: '',
    imgPath: '/images/sougijou/70/70_4.jpg',
  }, {
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/70/70_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/70/70_6.jpg',
  }],
  access: '東京メトロ丸の内線 「新高円寺駅」出口1・2より 徒歩8分。<br /><br />東京メトロ東西線 「中野駅」関東バス（中野～五日市街道営業所・吉祥寺）─杉並車庫前下車 徒歩3分。<br /><br />JR中央線 「高円寺駅」関東バス（五日市街道営業所行き）新高円寺下車 徒歩8分。<br /><br />JR中央線 「阿佐ヶ谷駅」都営・京王バス（阿佐ヶ谷～渋谷）杉並車庫前下車 徒歩3分。<br /><br />JR中央線 「中野駅」関東バス（中野～五日市街道営業所・吉祥寺）杉並車庫前下車 徒歩3分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/70/70_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '13',
  name: '愛染院',
  nameHira: 'あいぜんいん',
  description: '愛染院（愛染院会館）は、東京都練馬区にある寺院が運営する葬儀式場です。徳川将軍家から愛染院に発給した朱印状などで有名です。式場が3つあり規模にあわせて小式場・大式場・別館式場からお選びすることができます。',
  fullDescription: '最寄り駅からのアクセスは、都営大江戸線「練馬春日町駅」より徒歩3分です。式場の客席は第一式場80席、第二式場40席、別館30席で、全館利用も行えます。家族葬からご会葬のある大規模なお葬儀まで対応できる式場です。駐車場は80台までご利用いただけます。またお通夜の日の宿泊も可能です。通夜式と葬儀・告別式を行う葬儀式場としてお借りし、最寄りの火葬場へご案内いたします。施設の予約から葬儀のお手伝いまでセレモアにて承りますのでご相談ください。',
  address: '東京都練馬区春日町4-17-1',
  facilityDescription: '第一式場：80席　第二式場：40席　別館：30席',
  parking: '80台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '祭壇-1',
    description: '',
    imgPath: '/images/sougijou/13/13_1.jpg',
  }, {
    area: '祭壇-2',
    description: '',
    imgPath: '/images/sougijou/13/13_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/13/13_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/13/13_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/13/13_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/13/13_6.jpg',
  }],
  access: '都営大江戸線「練馬春日町駅」より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/13/13_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '14',
  name: '五百羅漢寺',
  nameHira: 'ごひゃくらかんじ',
  description: '五百羅漢寺（羅漢会館）は、東京都目黒区にある寺院が運営する葬儀式場です。<br /> 「目黒のらかんさん」として親しまれている天恩山五百羅漢寺の羅漢像は、五百体以上の群像が完成してから三百年<br /> の星霜を重ね、現在は東京都重要文化財に指定されています.',
  fullDescription: '五百羅漢寺（羅漢会館）は、家族葬から一般葬、社葬まであらゆる形態に対応する、お別れにふさわしい斎場です。1階には家族葬に最適な式場「清雲」、2階は規模や会葬者の人数により広さを変更できる式場「瑞光」、3階は会食会場「慈風」でゆったりと故人を偲ぶことができます。<br />「瑞光」は3分割で利用が可能で60席から最大180席まで広げて使用することができるので、あらゆる規模の葬儀に対応ができます。 東急目黒線「不動前駅」より徒歩6分の好立地の式場です。',
  address: '東京都目黒区下目黒3-19-1',
  facilityDescription: '清雲：30席　瑞光：60席～180席',
  parking: '20台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '2階式場エントランス',
    description: '',
    imgPath: '/images/sougijou/14/14_1.jpg',
  }, {
    area: '2階式場(瑞光)',
    description: '',
    imgPath: '/images/sougijou/14/14_2.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/14/14_3.jpg',
  }, {
    area: '3階遺族控室',
    description: '',
    imgPath: '/images/sougijou/14/14_4.jpg',
  }, {
    area: '3階会食会場 慈風',
    description: '',
    imgPath: '/images/sougijou/14/14_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/14/14_6.jpg',
  }],
  access: '東急目黒線「不動前駅」より徒歩6分。<br />JR山手線・東急目黒線・東京メトロ南北線「目黒駅」より徒歩12分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/14/14_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '15',
  name: '臨海斎場',
  nameHira: 'りんかいさいじょう',
  description: '臨海斎場は、港区、品川区、目黒区、大田区、世田谷区で構成される臨海部広域斎場組合が運営する式場と火葬場が併設された公営の斎場です。',
  fullDescription: '臨海部広域斎場組合が運営する式場と火葬場が併設された施設です。構成区は港区、品川区、目黒区、大田区、世田谷区となります。式場の席席は70席で、家族葬から会葬者をお迎えする一般葬まで、規模に応じて対応できる式場です。駐車場は1式場50台までご利用いただけます。<br />同じ施設内に火葬場と式場が併設しており、天候に左右されず、安心してご利用いただける斎場です。',
  address: '東京都大田区東海1-3-1',
  facilityDescription: '70席',
  parking: '249台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/15/15_1.jpg',
  }, {
    area: 'お清め室',
    description: '',
    imgPath: '/images/sougijou/15/15_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/15/15_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/15/15_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/15/15_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/15/15_6.jpg',
  }],
  access: '東京モノレール「流通センター駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/15/15_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '71',
  name: '池上本門寺',
  nameHira: 'いけがみほんもんじ',
  description: '池上本門寺は、700年以上の歴史のある日蓮宗大本山の寺院です。日蓮聖人ご入滅の霊場・布教の殿堂として東京都大田区に約7万坪の敷地を有しているお寺です。',
  fullDescription: '最寄り駅は 東急池上線 池上駅、都営浅草線 西馬込駅 より徒歩約10分です。お葬儀は日蓮宗の宗派に則った流れで行われ、本殿または松濤の間にて密葬から大規模な社葬まで行うことができます。<br /> バリアフリーに対応しているので、ご高齢の方や体が不自由な方にも安心です。',
  address: '東京都大田区池上1-1-1',
  facilityDescription: '200席',
  parking: '100台',
  fee: '',
  remarks: '檀家のみ可',
  facilityList: [{
    area: '大堂（祖師堂）',
    description: '',
    imgPath: '/images/sougijou/71/71_1.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/71/71_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/71/71_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/71/71_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/71/71_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/71/71_6.jpg',
  }],
  access: '東急池上線「池上駅」より徒歩10分。<br />都営浅草線「西馬込駅」南口より徒歩12分。<br />ＪＲ京浜東北線「大森駅」より池上駅行きバス（20分）「本門寺前」より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/71/71_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '72',
  name: '四ツ木斎場',
  nameHira: 'よつぎさいじょう',
  description: '四ツ木斎場は、東京都葛飾区にある火葬場が併設された民間の総合斎場です。式場と火葬場が併設なので、お車での移動がないので、ご負担が少なくなります。',
  fullDescription: '和モダンなやすらぎの空間を創出する四ツ木斎場は、お花茶屋駅から徒歩約5分のところにあり、葛飾区、足立区、墨田区、江戸川区北部の方など、広い範囲の方にご利用いただけます。「貴殯館」と呼ばれる最上グレードの火葬炉施設があります。<br /> 同じ施設内に火葬場と葬祭ホールを併設しており、天候に左右されず、安心してご利用いただける総合斎場です。',
  address: '東京都葛飾区白鳥2-9-1',
  facilityDescription: '最大 102席',
  parking: '60台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '貴殯館　ロビー',
    description: '',
    imgPath: '/images/sougijou/72/72_1.jpg',
  }, {
    area: '控室-1',
    description: '',
    imgPath: '/images/sougijou/72/72_2.jpg',
  }, {
    area: '控室-2',
    description: '',
    imgPath: '/images/sougijou/72/72_3.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/72/72_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/72/72_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/72/72_6.jpg',
  }],
  access: '京成上野線「お花茶屋駅」より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/72/72_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '73',
  name: '町屋斎場',
  nameHira: 'まちやさいじょう',
  description: '町屋斎場は、東京都荒川区にある火葬場が併設された民間の総合斎場です。式場と火葬場が併設なので、お車での移動がないので、ご負担が少なくなります。',
  fullDescription: '火葬場が式場に併設された施設として、首都圏最大の規模と設備を誇る町屋斎場は、お通夜、告別式、火葬までを同じ施設内で行える総合斎場です。家族葬から一般葬まで幅広くご利用いただけます。<br /> 京成上野線 町屋駅、東京メトロ千代田線 町屋駅より徒歩5分、また、都電荒川線 荒川七丁目駅より徒歩3分と最寄り駅からのアクセスも良い斎場です。',
  address: '東京都荒川区町屋1-23-4',
  facilityDescription: '雪：40席',
  parking: '50台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/73/73_1.jpg',
  }, {
    area: '控室-1',
    description: '',
    imgPath: '/images/sougijou/73/73_2.jpg',
  }, {
    area: '控室-2',
    description: '',
    imgPath: '/images/sougijou/73/73_3.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/73/73_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/73/73_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/73/73_6.jpg',
  }],
  access: '京成本線 「町屋駅」より徒歩5分。<br />東京メトロ千代田線 「町屋駅」1番出口より 徒歩5分。<br />東京さくらトラム（都電荒川線）「荒川七丁目駅」より 徒歩3分、「町屋駅前」より 徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/73/73_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '16',
  name: 'セレモア ガーデン会館 三鷹',
  nameHira: 'せれもあ がーでんかいかん みたか',
  description: 'ご家族で送るあたたかい家族葬・一日葬式場。永遠に心に残るお式のために、豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '東京都三鷹市新川5-16-10',
  facilityDescription: '',
  parking: '有り',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/16/16_1.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/16/16_2.jpg',
  }, {
    area: '遺族控室',
    description: '',
    imgPath: '/images/sougijou/16/16_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/16/16_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/16/16_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/16/16_6.jpg',
  }],
  access: 'JR中央線「三鷹駅」下車、南口7番乗り場「仙川」「晃華学園東」行、または8番乗り場「野ヶ谷」行きに乗車、「アジア・アフリカ語学院前」下車、すぐ前。<br /><br />JR中央線「吉祥寺駅」下車、南口6番乗り場「野ヶ谷」「調布駅北口」「深大寺」行き、または7番乗り場「仙川」「新川団地中央」行きに乗車、「アジア・アフリカ語学院前」下車、すぐ前。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/16/16_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/16/mitaka.png',
},
{
  id: '74',
  name: '禅林寺',
  nameHira: 'ぜんりんじ',
  description: '禅林寺は、東京都三鷹市にある黄檗宗の寺院で、霊泉斎場は家族葬から社葬・合同葬まで対応できる格式ある葬儀式場です。',
  fullDescription: '式場の客席は第一斎場が60席、第二斎場が40席で、家族葬から500名規模の社葬、合同葬まで対応が可能な式場です。宗教、宗派を問わずご利用いただけます。最寄り駅からのアクセスは、JR中央線「三鷹駅」南口より徒歩10分です。駐車場は92台完備しております。',
  address: '東京都三鷹市下連雀4-18-20',
  facilityDescription: '第一斎場：60席　第二斎場：40席',
  parking: '92台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/74/74_1.jpg',
  }, {
    area: '屋外テント',
    description: '',
    imgPath: '/images/sougijou/74/74_2.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/74/74_3.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/74/74_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/74/74_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/74/74_6.jpg',
  }],
  access: '中央線、総武線「三鷹駅」南口より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/74/74_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '17',
  name: '日華斎場',
  nameHira: 'にっかさいじょう',
  description: '日華斎場（多磨葬祭場）は府中市にあり、多摩霊園に隣接する式場です。葬儀式場と火葬施設が併設された利便性の高い式場で、家族葬から一般葬・社葬までご利用になれます。施設の予約から葬儀のお手伝いまでセレモアにて承ります。',
  fullDescription: '知名度が高く火葬場併設の民営の貸し式場です。バリアフリー設計、また火葬場が併設で雨天に左右されることなく安全・安心にご利用いただけます。多磨霊園に隣接するこちらの式場は、武蔵野の緑に囲まれた中で大切な方とのお別れの時間をお過ごしいただけます。35席の小式場（行華殿）が2部屋、お清め室は2階です。120～150名の大式場（思親殿）、2階のお清め室は80席です。仏教・神道・キリスト教・無宗教など宗教を問わずご利用いただけます。施設の予約から葬儀のお手伝いまでセレモアにて承りますのでご相談ください。',
  address: '東京都府中市多磨町2-1-1',
  facilityDescription: '思親殿：130席　行華殿：53席',
  parking: '55台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場　入口',
    description: '',
    imgPath: '/images/sougijou/17/17_1.jpg',
  }, {
    area: '行華殿',
    description: '',
    imgPath: '/images/sougijou/17/17_2.jpg',
  }, {
    area: '思親殿',
    description: '',
    imgPath: '/images/sougijou/17/17_3.jpg',
  }, {
    area: 'お清め室',
    description: '',
    imgPath: '/images/sougijou/17/17_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/17/17_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/17/17_6.jpg',
  }],
  access: '西武多摩川線　「多磨駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/17/17_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '18',
  name: 'セレモア ガーデン会館 国立',
  nameHira: 'せれもあ がーでんかいかん くにたち',
  description: 'ご遺族・ご親族様にも、ご会葬の方にもゆっくりと「大切なお別れ」の時をお過ごしいただくために、ゆったりとした空間でくつろぎの場を提供いたします。当会館では、ウィーンの伝統を現代に伝える名器ベーゼンドルファー（Model 170）を常設しており、皆様にご利用いただけます。',
  fullDescription: '',
  address: '東京都国立市谷保5115',
  facilityDescription: '第一式場： 60席　第二式場：18席',
  parking: '30台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/18/18_1.jpg',
  }, {
    area: 'ベーゼンドルファー',
    description: '',
    imgPath: '/images/sougijou/18/18_2.jpg',
  }, {
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/18/18_3.jpg',
  }, {
    area: '第二式場',
    description: '',
    imgPath: '/images/sougijou/18/18_4.jpg',
  }, {
    area: '2Fロビー',
    description: '',
    imgPath: '/images/sougijou/18/18_5.jpg',
  }, {
    area: '控室',
    description: '',
    imgPath: '/images/sougijou/18/18_6.jpg',
  }],
  access: 'JR南武線「谷保駅」下車、南口より徒歩３分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/18/18_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/18/kunitati.png',
},
{
  id: '19',
  name: 'セレモア立川会館 沙羅堂',
  nameHira: 'せれもあ たちかわかいかん さらどう',
  description: '荘厳で静かな空間は、ご遺族や参列される方々の心にゆとりと安心感を生みます。',
  fullDescription: '',
  address: '東京都立川市柏町1-26-4',
  facilityDescription: '65席',
  parking: '180台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/19/19_1.jpg',
  }, {
    area: '控室',
    description: '',
    imgPath: '/images/sougijou/19/19_2.jpg',
  }, {
    area: 'ご安置室',
    description: '',
    imgPath: '/images/sougijou/19/19_3.jpg',
  }, {
    area: '駐車場',
    description: '',
    imgPath: '/images/sougijou/19/19_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/19/19_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/19/19_6.jpg',
  }],
  access: 'JR中央線「立川駅」北口下車、多摩モノレール「立川北駅」より「上北台駅」行き乗車。「泉体育館」下車、すずかけ通り「幸町１丁目」交差点から西へ徒歩約8分。<br /><br />西武拝島線「玉川上水駅」下車、多摩モノレール「玉川上水駅」より「多摩センター駅」行き乗車。「泉体育館駅」下車、すずかけ通り「幸町１丁目」交差点から西へ徒歩約8分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/19/19_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/19/tachikawa_sarado.png',
},
{
  id: '20',
  name: 'セレモア メモリアルサロン ラピアン立川',
  nameHira: 'せれもあ めもりあるさろん らぴあんたちかわ',
  description: 'ご家族で送るあたたかい家族葬・一日葬式場。メモリアルサロン ラピアン立川は、個室のご安置から告別式当日まで、ゆっくりと最後のお別れを行うことができます。',
  fullDescription: 'ご家族で送るあたたかい家族葬・一日葬式場。メモリアルサロン ラピアン立川は、個室のご安置から告別式当日まで、ゆっくりと最後のお別れを行うことができます。<br>駐車場、宿泊設備、ご安置室完備されており、宗旨宗派問わずご利用可能。<br>駐車場、宿泊設備、ご安置室完備されており、隣には「お仏壇の東大和本店」がございます。敷地内に観音様がおられ、落ち着いた雰囲気のある空間でございます。家族葬から一般葬まで、宗旨宗派問わずご利用いただけます。',
  address: '東京都立川市柏町1-23-6',
  facilityDescription: '10席',
  parking: '30台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/20/20_1.jpg',
  }, {
    area: 'ラウンジ',
    description: '',
    imgPath: '/images/sougijou/20/20_2.jpg',
  }, {
    area: 'ご安置室-1',
    description: '',
    imgPath: '/images/sougijou/20/20_3.jpg',
  }, {
    area: 'ご安置室-2',
    description: '',
    imgPath: '/images/sougijou/20/20_4.jpg',
  }, {
    area: 'ご安置室-3',
    description: '',
    imgPath: '/images/sougijou/20/20_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/20/20_6.jpg',
  }],
  access: 'JR中央線「立川駅」北口より、多摩モノレール「立川北駅」で乗り換え。「泉体育館駅」で下車し、徒歩約10分。<br /><br />西武拝島線「玉川上水駅」より、多摩モノレール「玉川上水駅」で乗り換え。「砂川七番駅」で下車し、徒歩約10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/20/20_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/20/memorialsalon_rapian.png',
},
{
  id: '21',
  name: 'セレモア ガーデン会館 玉川上水',
  nameHira: 'せれもあ がーでんかいかん たまがわじょうすい',
  description: 'ご遺族・ご親族様にも、ご会葬の方にもゆっくりと「大切なお別れ」の時をお過ごしいただくために、ゆったりとした空間でくつろぎの場を提供いたします。当会館では、ウィーンの伝統を現代に伝える名器ベーゼンドルファー（第一式場にModel 155、第二式場にModel 130）を常設しており、皆様にご利用いただけます。',
  fullDescription: '',
  address: '東京都東大和市桜ヶ丘2-208-1',
  facilityDescription: '第一式場：100席　第二式場：30席',
  parking: '60台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/21/21_1.jpg',
  }, {
    area: 'アプローチ',
    description: '',
    imgPath: '/images/sougijou/21/21_2.jpg',
  }, {
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/21/21_3.jpg',
  }, {
    area: 'ベーゼンドルファー/祭壇',
    description: '',
    imgPath: '/images/sougijou/21/21_4.jpg',
  }, {
    area: 'ベーゼンドルファー',
    description: '',
    imgPath: '/images/sougijou/21/21_5.jpg',
  }, {
    area: '献歌',
    description: '',
    imgPath: '/images/sougijou/21/21_6.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/21/21_7.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/21/21_8.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/21/21_9.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/21/21_10.jpg',
  }],
  access: '多摩都市モノレール「桜街道駅」より徒歩3分。<br />西武拝島線「玉川上水駅」北口より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/21/21_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/21/garden_tamagawa.png',
},
{
  id: '22',
  name: 'セレモア 東大和会館',
  nameHira: 'せれもあ ひがしやまとかいかん',
  description: '最期のお別れに相応しい格調高いお葬儀と、お集まりになるすべての皆様に、安らぎの空間をお約束いたします。豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '東京都東大和市南街1-11-9',
  facilityDescription: '100席',
  parking: '20台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/22/22_1.jpg',
  }, {
    area: '控室',
    description: '',
    imgPath: '/images/sougijou/22/22_2.jpg',
  }, {
    area: '法要室',
    description: '',
    imgPath: '/images/sougijou/22/22_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/22/22_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/22/22_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/22/22_6.jpg',
  }],
  access: '西武拝島線「東大和市駅」北口、またはJR中央線「立川駅」北口8番のりばより、西武バス「イオンモール」「東村山駅」行き乗車。「東大和病院」下車。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/22/22_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/22/higasiyamato.png',
},
{
  id: '23',
  name: 'セレモア ガーデン会館 昭島',
  nameHira: 'せれもあ がーでんかいかん あきしま',
  description: 'ご遺族・ご親族様にも、ご会葬の方にもゆっくりと「大切なお別れ」の時をお過ごしいただくために、ゆったりとした空間でくつろぎの場を提供いたします。当会館では、ピアノの調べに大切な方への想いをのせて、最期のお別れをお手伝いさせていただきます。常設しているピアノは、皆様でご利用いただけます。どうぞご遠慮なくご相談くださいませ。',
  fullDescription: '',
  address: '東京都昭島市玉川町2-4-12',
  facilityDescription: '第一式場：74席　第二式場：24席',
  parking: '20台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/23/23_1.jpg',
  }, {
    area: 'ピアノ常設',
    description: '',
    imgPath: '/images/sougijou/23/23_2.jpg',
  }, {
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/23/23_3.jpg',
  }, {
    area: '第二式場',
    description: '',
    imgPath: '/images/sougijou/23/23_4.jpg',
  }, {
    area: '1Fホワイエ',
    description: '',
    imgPath: '/images/sougijou/23/23_5.jpg',
  }, {
    area: '控室',
    description: '',
    imgPath: '/images/sougijou/23/23_6.jpg',
  }],
  access: 'JR青梅線「東中神駅」南口より徒歩5分<br />JR青梅線「中神駅」南口より徒歩７分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/23/23_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/23/garden_akisima.png',
},
{
  id: '24',
  name: 'セレモア ガーデン会館 福生',
  nameHira: 'せれもあ がーでんかいかん ふっさ',
  description: 'ご家族で送るあたたかい家族葬・一日葬式場。国道16号に面しており、東京都内や埼玉・神奈川方面から車でお越しの方もご利用しやすい家族葬専用の葬儀式場。お葬儀は一日一組のみ。',
  fullDescription: '',
  address: '東京都福生市熊川1311',
  facilityDescription: '20席',
  parking: 'あり',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/24/24_1.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/24/24_2.jpg',
  }, {
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/24/24_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/24/24_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/24/24_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/24/24_6.jpg',
  }],
  access: 'JR青梅線・西武拝島線とも「拝島駅」の西武拝島線側口下車、徒歩約13分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/24/24_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/24/gardern_hukuoi.png',
},
{
  id: '25',
  name: 'セレモア 八王子大横町会館',
  nameHira: 'せれもあ はちおうじおおよこちょうかいかん',
  description: '最期のお別れに相応しい格調高いお葬儀と、お集まりになるすべての皆様に、安らぎの空間をお約束いたします。豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '東京都八王子市大横町14-22',
  facilityDescription: '第一式場：60席　中式場：40席　第二式場：20席',
  parking: '30台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/25/25_1.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/25/25_2.jpg',
  }, {
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/25/25_3.jpg',
  }, {
    area: '喪主挨拶',
    description: '',
    imgPath: '/images/sougijou/25/25_4.jpg',
  }, {
    area: '出棺',
    description: '',
    imgPath: '/images/sougijou/25/25_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/25/25_6.jpg',
  }],
  access: 'JR中央線「八王子駅」下車、北口バス停11番、14番のりば、または「京王八王子駅」下車、4番のりばより、「みつい台（八日町経由）」「純心女子学園（左入経由）」「創価大学循環（八日町経由）」行に乗車、「八日町四丁目」下車、進行方向左側。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/25/25_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/25/hachiozi_oyoko.png',
},
{
  id: '26',
  name: 'セレモア ガーデン会館 京王片倉駅前',
  nameHira: 'せれもあ がーでんかいかん けいおうかたくらえきまえ',
  description: '最期のお別れに相応しい格調高いお葬儀と、お集まりになるすべての皆様に、安らぎの空間をお約束いたします。豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '東京都八王子市片倉町492-10',
  facilityDescription: '60席',
  parking: '20台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/26/26_1.jpg',
  }, {
    area: '第一式場',
    description: '',
    imgPath: '/images/sougijou/26/26_2.jpg',
  }, {
    area: '遺族控室',
    description: '',
    imgPath: '/images/sougijou/26/26_3.jpg',
  }, {
    area: '導師控室',
    description: '',
    imgPath: '/images/sougijou/26/26_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/26/26_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/26/26_6.jpg',
  }],
  access: '京王高尾線「京王片倉駅」下車、徒歩約3分。<br />JR横浜線「片倉駅」下車、徒歩約5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/26/26_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/26/garden_keio.png',
},
{
  id: '27',
  name: 'セレモア ガーデン会館 八王子西',
  nameHira: 'せれもあ がーでんかいかん はちおうじにし',
  description: '永遠に心に残るお式のために、豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '東京都八王子市大楽寺町128',
  facilityDescription: '式場：60席',
  parking: '60台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/27/27_1.jpg',
  }, {
    area: '遺族控室',
    description: '',
    imgPath: '/images/sougijou/27/27_2.jpg',
  }, {
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/27/27_3.jpg',
  }, {
    area: 'アーチ',
    description: '',
    imgPath: '/images/sougijou/27/27_4.jpg',
  }, {
    area: 'AED',
    description: '',
    imgPath: '/images/sougijou/27/27_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/27/27_6.jpg',
  }],
  access: 'JR中央線「八王子駅」下車、八王子駅北口バス停9番のりばよりまたは京王線「京王八王子駅」下車、京王八王子駅バスターミナル2番のりばより約25分、「神戸」下車、前方左側。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/27/27_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/27/garden_hachiozinishi.png',
},
{
  id: '28',
  name: '楢原斎場',
  nameHira: 'ならはらさいじょう',
  description: '楢原斎場は、八王子市の公営斎場です。家族葬から大規模な社葬まで使用することができます。施設の予約から葬儀のお手伝いまでセレモアにて承ります。',
  fullDescription: '楢原斎場はどなたでもご利用可能ですが、公営斎場のため八王子市民と八王子市民外の方では利用料金が異なります。宗教形式も仏教・神道・キリスト教・無宗教など問いません。第一・第二・第三式場は各72席ですが、大規模な場合第一・第二式場は間仕切りを外し、最大150席の式場として利用可能です。（葬儀式場を2室ご利用になる場合は、2室分の利用料金がかかります）駐車場は300台までご利用いただけ、少人数の家族葬から大規模な社葬まで幅広くご利用されております。',
  address: '東京都八王子市楢原町1578-5',
  facilityDescription: '第一式場：72席　第二式場：72席　第三式場：72席　第四式場：30席',
  parking: '300台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/28/28_1.jpg',
  }, {
    area: '御霊入場',
    description: '',
    imgPath: '/images/sougijou/28/28_2.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/28/28_3.jpg',
  }, {
    area: '待合ロビー',
    description: '',
    imgPath: '/images/sougijou/28/28_4.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/28/28_5.jpg',
  }, {
    area: '第三・第四式場',
    description: '',
    imgPath: '/images/sougijou/28/28_6.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/28/28_7.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/28/28_8.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/28/28_9.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/28/28_10.jpg',
  }],
  access: 'ＪＲ八王子駅（中央線・横浜線・八高線）下車、バス約25分。北口バスターミナル7番乗場「武蔵五日市・楢原町・川口小学校・上川霊園・今熊行き」→楢原町バス停下車、徒歩7分。<br /><br />京王八王子駅（京王線）下車、バス約30分。バスターミナル3番乗場「武蔵五日市・楢原町・川口小学校・上川霊園・今熊行き」→楢原町バス停下車、徒歩7分。<br /><br />西八王子駅（中央線）下車、バス約20分。北口1番乗場「楢原町・川口小学校」→楢原町バス停下車、徒歩7分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/28/28_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '29',
  name: '總持寺',
  nameHira: 'そうじじ',
  description: '總持寺（三松閣）は、曹洞宗の大本山で神奈川県横浜市鶴見区にある寺院が運営する葬儀式場です。三松閣は伝統と風格のある外観で荘厳なお葬儀の空間を作ることができます。能登・祖院にあった三本の龍形の松にちなみ「三松閣」と呼ばれています。',
  fullDescription: '總持寺（三松閣）は、神奈川県横浜市鶴見区にあり最寄り駅からのアクセスは、JR京浜東北線「鶴見駅」より徒歩7分です。式場の客席は200席ですが、家族葬からご会葬のある500名から1,000名規模のお葬儀も可能で規模に応じて対応できる式場です。また駐車場は200台までご利用いただけます。施設の予約から葬儀のお手伝いまでセレモアにて承りますのでご相談ください。',
  address: '神奈川県横浜市鶴見区鶴見2-1-1',
  facilityDescription: '200席',
  parking: '200台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/29/29_1.jpg',
  }, {
    area: '仏殿',
    description: '',
    imgPath: '/images/sougijou/29/29_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/29/29_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/29/29_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/29/29_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/29/29_6.jpg',
  }],
  access: 'JR京浜東北線「鶴見駅」より徒歩7分。京浜急行線「鶴見駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/29/29_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '30',
  name: '妙蓮寺',
  nameHira: 'みょうれんじ',
  description: '妙蓮寺（妙蓮寺斎場）は、神奈川県横浜市港北区にある寺院が運営する葬儀式場です。落ち着いた雰囲気の中、心安らかなお別れの場としてふさわしい、気品高い空間です。<br /> また、どなたにとっても優しいバリアフリー設計を採用しています。',
  fullDescription: '妙蓮寺（妙蓮寺斎場）は、神奈川県港北区にあり最寄り駅からのアクセスは、東急東横線「妙蓮寺駅」より徒歩すぐです。式場の席数は第一斎場（釈迦堂）100席、第二斎場（祖師堂）40席、蓮華の間10席で、家族葬からご会葬のある葬儀まで規模に応じたお葬儀に対応できる式場です。大規模な社葬の場合は第一斎場（釈迦堂）と第二斎場（祖師堂）を合わせ全館でもご利用いただけます。駐車場はかぎりがありますが30台までご利用いただけます。施設の予約から葬儀のお手伝いまでセレモアにて承りますのでご相談ください。',
  address: '神奈川県横浜市港北区菊名2-1-5',
  facilityDescription: '第一斎場(釈迦堂)：100席　第二斎場(祖師堂)：40席　蓮華の間：10席',
  parking: '30台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '山門',
    description: '',
    imgPath: '/images/sougijou/30/30_1.jpg',
  }, {
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/30/30_2.jpg',
  }, {
    area: '第一斎場（釈迦堂）',
    description: '',
    imgPath: '/images/sougijou/30/30_3.jpg',
  }, {
    area: '第二斎場（祖師堂）',
    description: '',
    imgPath: '/images/sougijou/30/30_4.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/30/30_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/30/30_6.jpg',
  }],
  access: '東急東横線　「妙蓮寺駅」より徒歩すぐ。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/30/30_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '31',
  name: 'セレモア 坂戸駅前会館',
  nameHira: 'せれもあ さかどえきまえかいかん',
  description: '最期のお別れに相応しい格調高いお葬儀と、お集まりになるすべての皆様に、安らぎの空間をお約束いたします。豊富な経験と実績を持つ弊社スタッフが親身になって皆様のお手伝いをさせていただきます。',
  fullDescription: '',
  address: '埼玉県坂戸市日の出町31-13',
  facilityDescription: '第一式場：100席　第二式場：30席',
  parking: '70台',
  fee: '式場使用料：お問合せください。',
  remarks: '宗派限定なし',
  facilityList: [{
    area: '受付',
    description: '',
    imgPath: '/images/sougijou/31/31_1.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/31/31_2.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/31/31_3.jpg',
  }, {
    area: '葬儀委員長 謝辞',
    description: '',
    imgPath: '/images/sougijou/31/31_4.jpg',
  }, {
    area: '弔辞',
    description: '',
    imgPath: '/images/sougijou/31/31_5.jpg',
  }, {
    area: '出棺',
    description: '',
    imgPath: '/images/sougijou/31/31_6.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/31/31_7.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/31/31_8.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/31/31_9.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/31/31_10.jpg',
  }],
  access: '東武東上線「坂戸駅」より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/31/31_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/31/sakatostation.png',
},
{
  id: '32',
  name: 'セレモア ガーデン会館 所沢駅西口',
  nameHira: 'せれもあ がーでんかいかん ところざわえきにしぐち',
  description: '所沢駅西口より徒歩3分。所沢パークホテル隣にございます。',
  fullDescription: '',
  address: '埼玉県所沢市東住吉4-7',
  facilityDescription: '30席',
  parking: '駐車場有り',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/32/32_1.jpg',
  }, {
    area: '祭壇1',
    description: '',
    imgPath: '/images/sougijou/32/32_2.jpg',
  }, {
    area: '祭壇2',
    description: '',
    imgPath: '/images/sougijou/32/32_3.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/32/32_4.jpg',
  }, {
    area: '遺族控室',
    description: '',
    imgPath: '/images/sougijou/32/32_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/32/32_6.jpg',
  }],
  access: '所沢駅西口より徒歩3分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/32/32_main.jpg',
  hasMorgue: true,
  ceremore: true,
  ceremoreFullLogo: '/images/sougijou/32/tokorosawa_station.png',
},
{
  id: '33',
  name: '信行寺',
  nameHira: 'しんぎょうじ',
  description: '信行寺（春秋苑）は、神奈川県川崎市多摩区にある寺院が運営する葬儀式場です。とても広大な敷地にあり緑に囲まれた中で大切な方とのお別れの時間をお過ごしいただける式場です。',
  fullDescription: '信行寺（春秋苑）は、神奈川県川崎市多摩区にあり最寄り駅からのアクセスは、小田急多摩線「生田駅」より徒歩10分です。式場の客席は白蓮華堂400席、礼拝堂60席、青蓮堂40席で、家族葬からご会葬のある葬儀まで規模に応じたお葬儀に対応できる式場です。大規模な社葬も安心してご利用いただけます。駐車場も広く200台までご利用いただけます。施設の予約から葬儀のお手伝いまでセレモアにて承りますのでご相談ください。',
  address: '神奈川県川崎市多摩区南生田8-1-1',
  facilityDescription: '白蓮華堂：400席　礼拝堂：60席　青蓮堂：40席',
  parking: '200台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '式場　入口',
    description: '',
    imgPath: '/images/sougijou/33/33_1.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/33/33_2.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/33/33_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/33/33_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/33/33_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/33/33_6.jpg',
  }],
  access: '小田急多摩線「生田駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/33/33_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '34',
  name: '昌平寺',
  nameHira: 'しょうへいじ',
  description: '昌平寺は最寄り駅の所沢駅からは徒歩で約10分(車で5分)と<br /> 交通の便も良く、所沢市斎場へのアクセスも車で5分程で<br /> 到着可能な葬儀式場です。',
  fullDescription: '昌平寺は家族葬、一般葬から社葬まで対応が可能です。駐車場と宿泊設備もございます。全館バリアフリーなので、安心してご利用いただけます。広いロビーと室内での受付もあり、また、ご出棺時やお車での乗降の際、雨に濡れる心配がございません。 各式場の控室には専用の浴室が完備されており、夜間の宿泊も可能です。',
  address: '埼玉県所沢市西新井町9-4',
  facilityDescription: '第一式場：30席　第二式場：60席　全館：100席',
  parking: '40台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/34/34_1.jpg',
  }, {
    area: '本堂',
    description: '',
    imgPath: '/images/sougijou/34/34_2.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/34/34_3.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/34/34_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/34/34_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/34/34_6.jpg',
  }],
  access: '西武新宿線「所沢駅」よりタクシーにて5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/34/34_main.jpg',
  hasMorgue: true,
  ceremore: false,
},
{
  id: '35',
  name: '所沢市斎場',
  nameHira: 'ところざわしさいじょう',
  description: '所沢市斎場は所沢市が運営する式場と火葬場が併設の公営施設です。<br /> 式場には霊安室も完備されておりご利用いただけます。',
  fullDescription: '所沢市斎場は市民はもちろん所沢市民以外の方でもご利用いただけます。4つのタイプがある式場は、家族葬や一般葬から社葬まで対応が可能です。火葬場併設なので、移動の負担が軽減されます。また、共同のシャワー室が2室あり通夜日の宿泊が可能です。その他、施設内には売店が設置されており、不祝儀袋、数珠、飲物、おつまみ等の購入が出来、火葬の待ち時間を利用してご利用することが出来ます。',
  address: '埼玉県所沢市北原町1282',
  facilityDescription: '第1式場：85席　第2式場：50席　3式場：50席　第5式場：40席',
  parking: '202台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/35/35_1.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/35/35_2.jpg',
  }, {
    area: '式場',
    description: '',
    imgPath: '/images/sougijou/35/35_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/35/35_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/35/35_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/35/35_6.jpg',
  }],
  access: '西武新宿線「航空公園駅」からタクシーにて10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/35/35_main.jpg',
  hasMorgue: true,
  ceremore: false,
},];

export const HOTELS: Facility[] = [{
  id: '75',
  name: '浅草ビューホテル',
  nameHira: 'あさくさびゅーほてる',
  description: '浅草ビューホテルは日本の古き良き雰囲気を体感できる浅草<br /> エリアの中心部にあり、浅草の風景や東京スカイツリー、<br /> 都内のシティビューを一望出来るホテルです。',
  fullDescription: '浅草ビューホテルでは大小９つの個性豊かな宴会場があります。<br /> 大宴会場の飛翔は浅草ビューホテルで最大の規模と華やかさを誇るメインバンケットで、パーテーションで区切り、式典・献花会場、懇談会場と分けてお別れの会、偲ぶ会を執り行うことが可能です。<br /> 大小様々な会場は規模、用途などご希望に合わせて対応が可能です。',
  address: '東京都台東区西浅草3-17-1',
  facilityDescription: '大小9宴会場　大宴会場｢飛翔｣最大収容人数1,000名',
  parking: '180台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/75/75_1.jpg',
  }, {
    area: 'スカイダイニング',
    description: '',
    imgPath: '/images/sougijou/75/75_2.jpg',
  }, {
    area: '飛翔',
    description: '',
    imgPath: '/images/sougijou/75/75_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/75/75_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/75/75_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/75/75_6.jpg',
  }],
  access: 'つくばエクスプレス浅草駅から直結<br />田原町駅から徒歩7分<br />都営浅草駅から徒歩10分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/75/75_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '76',
  name: '学士会館',
  nameHira: 'がくしかいかん',
  description: '学士会館は昭和３年、関東大震災の復興の灯として東京大学発祥の地に誕生いたしました。現存する数少ない昭和初期の建築様式を保ち、９０年以上の歴史を刻んできました。',
  fullDescription: '学士会館では小規模な宴会から200～300名規模の宴会まで、用途に合わせてご利用いただける多彩なバンケットルームを備えております。建設当時の姿が残る格調高いメインバンケットルーム、5.2ｍの天井高とオニキスの装飾が壁を彩る雰囲気ある装飾のバンケットルーム、モダンな雰囲気の学士会館最大のバンケットルームでお別れの会、偲ぶ会、法要を執り行うことが可能です。',
  address: '東京都千代田区神田錦町3-28',
  facilityDescription: '大小 全15宴会場　大宴会場「201号室」　最大収容人数300名',
  parking: '17台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '201号室',
    description: '',
    imgPath: '/images/sougijou/76/76_1.jpg',
  }, {
    area: '202号室',
    description: '',
    imgPath: '/images/sougijou/76/76_2.jpg',
  }, {
    area: '210号室',
    description: '',
    imgPath: '/images/sougijou/76/76_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/76/76_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/76/76_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/76/76_6.jpg',
  }],
  access: '都営三田線／都営新宿線／東京メトロ半蔵門線　神保町」駅下車A9出口から徒歩1分<br /><br />東京メトロ東西線「竹橋」駅下車３a出口から徒歩5分<br /><br />JR中央線／総武線「御茶ノ水」駅下車御茶ノ水橋口から徒歩15分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/76/76_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '36',
  name: 'グランドニッコー東京 台場',
  nameHira: 'ぐらんどにっこーとうきょうだいば',
  description: '東京タワーやレインボーブリッジなど、お台場を一望するホテルです。<br /> 小・中・大宴会場から高層宴会場まで、規模やご希望に合わせたお別れの会に対応が可能です。',
  fullDescription: '最大収容人数1200名超の大宴会場『パレロワイヤル』をはじめとした数々のバンケットルームは、あらゆる規模のお別れの会でご利用いただけます。また、地上100メートルからの東京ベイを一望できる、都内最大級の高層宴会場では、窓一面に広がる東京 お台場の眺望が開放感を演出します。',
  address: '東京都港区台場2-6-1',
  facilityDescription: '大小 全17宴会場　大宴会場「パレロワイヤル」最大収容人数1,200名',
  parking: '374台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '1F エントランスホール',
    description: '',
    imgPath: '/images/sougijou/36/36_1.jpg',
  }, {
    area: 'B1F ホワイエ',
    description: '',
    imgPath: '/images/sougijou/36/36_2.jpg',
  }, {
    area: 'パレロワイヤル',
    description: '',
    imgPath: '/images/sougijou/36/36_3.jpg',
  }, {
    area: '外観-1',
    description: '',
    imgPath: '/images/sougijou/36/36_4.jpg',
  }, {
    area: '外観-2',
    description: '',
    imgPath: '/images/sougijou/36/36_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/36/36_6.jpg',
  }],
  access: 'りんかい線「東京テレポート駅」より徒歩10分。ゆりかもめ「台場駅」より徒歩すぐ',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/36/36_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '37',
  name: 'グランドプリンスホテル新高輪',
  nameHira: 'ぐらんどぷりんすほてるしんたかなわ',
  description: '東京の新たな玄関口 品川に位置する、都内有数の日本庭園を有する伝統と先進性に富んだトラディショナルなホテルです。',
  fullDescription: '都心にありながら約2万㎡の日本庭園を有し、四季折々の自然を感じられるやすらぎの空間が広がる品川高輪エリアには、ザ・プリンス さくらタワー東京、グランドプリンスホテル高輪、グランドプリンスホテル新高輪の3つのホテルが特別な空間を演出してくれます。<br /> 品川駅高輪口から徒歩約5分の好立地の3ホテルは、最大収容人数2,500名以上の国際館パミール崑崙をはじめ、飛天、北辰ほか、様々な規模の62の会場で、あらゆるお別れの会、偲ぶ会に対応が可能です。',
  address: '東京都港区高輪3-13-1',
  facilityDescription: '大小 全62宴会場　大宴会場「崑崙」最大収容人数2,500名',
  parking: '1,000台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'パミール　入口',
    description: '',
    imgPath: '/images/sougijou/37/37_1.jpg',
  }, {
    area: '受付',
    description: '',
    imgPath: '/images/sougijou/37/37_2.jpg',
  }, {
    area: '懇談会場',
    description: '',
    imgPath: '/images/sougijou/37/37_3.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/37/37_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/37/37_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/37/37_6.jpg',
  }],
  access: '都営地下鉄浅草線「高輪台駅」より徒歩約3分。新幹線・JR線・京急線「品川駅」高輪口より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/37/37_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '38',
  name: 'グランドプリンスホテル高輪',
  nameHira: 'ぐらんどぷりんすほてるたかなわ',
  description: '東京の新たな玄関口 品川に位置する、都内有数の日本庭園を有する伝統と先進性に富んだトラディショナルなホテルです。',
  fullDescription: '都心にありながら約2万㎡の日本庭園を有し、四季折々の自然を感じられるやすらぎの空間が広がる品川高輪エリアには、ザ・プリンス さくらタワー東京、グランドプリンスホテル高輪、グランドプリンスホテル新高輪の3つのホテルが特別な空間を演出してくれます。<br /> 品川駅高輪口から徒歩約5分の好立地の3ホテルは、最大収容人数2,500名以上の国際間パミール崑崙をはじめ、飛天、北辰ほか、様々な規模の62の会場で、あらゆるお別れの会、偲ぶ会に対応が可能です。',
  address: '東京都港区高輪3-13-1',
  facilityDescription: '大小 全62宴会場　大宴会場「崑崙」最大収容人数2,500名',
  parking: '1,000台',
  fee: '',
  remarks: '',
  facilityList: [],
  access: '都営地下鉄浅草線「高輪台駅」より徒歩約3分。新幹線・JR線・京急線「品川駅」高輪口より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/38/38_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '39',
  name: '京王プラザホテル新宿',
  nameHira: 'けいおうぷらざほてるしんじゅく',
  description: '京王プラザホテルは、国内最大の乗降客数の新宿エリアを代表するホテルです。<br /> 1971年、日本初の超高層ホテルとして誕生した歴史と格式のあるホテルです。',
  fullDescription: '京王プラザホテルには、大小38のバリエーション豊富な宴会場があります。1,500名規模の大人数を収容できる大宴会場「コンコードボールルーム」や宴会場保有数は新宿最大級です。<br /> お客様の多彩なニーズに対応できること、充実したサービス、新宿駅からのアクセスの良さで、あらゆる規模、ご希望のお別れの会、偲ぶ会のご提案が可能です。',
  address: '東京都新宿区西新宿2-2-1',
  facilityDescription: '大小 全38宴会場　大宴会場「コンコードボールルーム」最大収容人数1,500名',
  parking: '509台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/39/39_1.jpg',
  }, {
    area: 'コンコードボールルーム-1',
    description: '',
    imgPath: '/images/sougijou/39/39_2.jpg',
  }, {
    area: 'コンコードボールルーム-2',
    description: '',
    imgPath: '/images/sougijou/39/39_3.jpg',
  }, {
    area: 'エミネンスホール',
    description: '',
    imgPath: '/images/sougijou/39/39_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/39/39_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/39/39_6.jpg',
  }],
  access: 'JR線「新宿駅」西口より徒歩5分。都営大江戸線「都庁前駅」より徒歩すぐ。',
  caseCategory: 'owakarenokai',
  caseId: '003',
  imagePath: '/images/sougijou/39/39_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '41',
  name: '京王プラザホテル八王子',
  nameHira: 'けいおうぷらざほてるはちおうじ',
  description: '京王プラザホテル八王子は、京王線京王八王子駅下車徒歩3分、JR八王子駅北口前の好立地な西東京地区最大規模の格式あるホテルです。',
  fullDescription: '京王プラザホテル八王子には、大小10のバリエーション豊富な宴会場があります。立食700名規模の大人数を収容できる大宴会場「翔王」や、宴会場保有数は西東京エリア最大級です。<br /> お客様の多彩なニーズに対応できること、充実したサービス、新宿駅からのアクセスの良さで、あらゆる規模、ご希望のお別れの会、偲ぶ会のご提案が可能です。',
  address: '東京都八王子市旭町14-1',
  facilityDescription: '大小 全10宴会場　大宴会場「翔王」最大収容人数1,000名',
  parking: '154台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '翔王の間',
    description: '',
    imgPath: '/images/sougijou/41/41_1.jpg',
  }, {
    area: '宴',
    description: '',
    imgPath: '/images/sougijou/41/41_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/41/41_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/41/41_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/41/41_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/41/41_6.jpg',
  }],
  access: '京王線「京王八王子駅」より徒歩3分。JR線「八王子駅」北口より徒歩すぐ。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/41/41_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '42',
  name: 'ザ・キャピトルホテル東急',
  nameHira: 'ざ・きゃぴとるほてるとうきゅう',
  description: '東京・永田町にあるザ・キャピトルホテル東急は、銀座線・南北線 溜池山王駅直結の好立地ながら、隣接する日枝神社の豊かな緑に囲まれたラグジュアリーホテルです。',
  fullDescription: '東京の中心に位置する永田町、国会議事堂前駅、溜池山王駅、地下鉄4線乗り入れ地下直結という利便性はあらゆるお集まりに最適です。雨天時も影響を受けずにお越しいただけます。<br /> 落ち着きと気品に満ちた大宴会場「鳳凰」をはじめ、中・小の豊富な宴会場は、お別れの会、偲ぶ会、各種法要など、ご希望に合わせご利用いただけます。',
  address: '東京都千代田区永田町2-10-3',
  facilityDescription: '大小 全5宴会場　大宴会場「鳳凰」最大収容人数500名',
  parking: '150台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '献花会場',
    description: '',
    imgPath: '/images/sougijou/42/42_1.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/42/42_2.jpg',
  }, {
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/42/42_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/42/42_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/42/42_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/42/42_6.jpg',
  }],
  access: '千代田線・丸ノ内線「国会議事堂前駅」、銀座線・南北線「溜池山王駅」より徒歩すぐ。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/42/42_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '43',
  name: '渋谷エクセルホテル東急',
  nameHira: 'しぶやえくせるほてるとうきゅう',
  description: '渋谷エクセルホテル東急は、渋谷駅直結（渋谷マークシティ内）でアクセスの良いホテルです。ナチュラルでモダンな客室や、地上100mの眺望と美食をお楽しみいただけるレストランを備え、洗練されたくつろぎの空間を持つホテルです。',
  fullDescription: '華やかな中にも落ち着きのある大宴会場「プラネッツルーム」をはじめ、中・小規模の豊富な宴会場は、お別れの会、偲ぶ会、各種方法など、ご希望に合わせご利用いただけます。',
  address: '東京都渋谷区道玄坂1-12-2',
  facilityDescription: '大小 全3宴会場　大宴会場「プラネッツルーム」最大収容人数200名',
  parking: '100台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'プラネッツルーム',
    description: '',
    imgPath: '/images/sougijou/43/43_1.jpg',
  }, {
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/43/43_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/43/43_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/43/43_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/43/43_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/43/43_6.jpg',
  }],
  access: 'JR線「渋谷駅」中央改札より徒歩3分。<br />東急東横線・東急田園都市線・半蔵門線・副都心線「渋谷駅」出口A5より徒歩1分。<br />銀座線「渋谷駅」スクランブルスクエア方面改札より徒歩5分。<br />京王井の頭線「渋谷駅」中央口改札より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/43/43_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '44',
  name: '品川プリンスホテル',
  nameHira: 'しながわぷりんすほてる',
  description: '品川プリンスホテルは、東京都港区にある日本最大級の客室数3,679室を誇るシティホテルです。1978年に旧毛利元道公爵邸跡地に開業しました。',
  fullDescription: '品川プリンスホテルのメインタワー、アネックスタワー、Nタワーには大小さまざまな宴会場があります。中でもアネックスタワー5Fにある2,400名収容のプリンスホールは、9つのスペースに分割が可能で、ご希望に合わせ献花会場、懇談会場、控室としてのご利用が可能です。',
  address: '東京都港区高輪4-10-30',
  facilityDescription: '大小 全22宴会場　大宴会場「プリンスルーム」最大収容人数2,400名',
  parking: '760台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'プリンスホール',
    description: '',
    imgPath: '/images/sougijou/44/44_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/44/44_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/44/44_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/44/44_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/44/44_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/44/44_6.jpg',
  }],
  access: '新幹線・JR線・京急線「品川駅」高輪口より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/44/44_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '45',
  name: 'セルリアンタワー東急ホテル',
  nameHira: 'せるりあんたわーとうきゅうほてる',
  description: 'セルリアンタワー東急ホテルは、渋谷駅徒歩5分の抜群の交通アクセスを誇る恵まれた立地、充実した映像・音響・照明設備の渋谷エリアを代表するホテルです。',
  fullDescription: 'セルリアンタワー東急ホテルのボールルームは、天井高7.2メートルを誇る開放的な空間で、4つのスペースに分割が可能で、ご希望に合わせ式典会場、献花会場、懇談会場として大規模なお別れの会、偲ぶ会のご利用が可能です。<br /> また、大・中・小さまざまな宴会場は、お別れの会、偲ぶ会、各種法要など、ご希望に合わせご利用いただけます。',
  address: '東京都渋谷区桜丘町26-1',
  facilityDescription: '大小 全11宴会場　大宴会場「セルリアンタワーボールルーム」最大収容人数1,300名',
  parking: '375台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'ボールルーム',
    description: '',
    imgPath: '/images/sougijou/45/45_1.jpg',
  }, {
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/45/45_2.jpg',
  }, {
    area: '外観',
    description: '',
    imgPath: '/images/sougijou/45/45_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/45/45_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/45/45_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/45/45_6.jpg',
  }],
  access: 'JR線「渋谷駅」西口より徒歩5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/45/45_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '46',
  name: '帝国ホテル東京',
  nameHira: 'ていこくほてるとうきょう',
  description: '帝国ホテル東京はホテル御三家のひとつで、千代田区にある日本を代表するホテルです。<br /> 1890年海外からの賓客を迎える「日本の迎賓館」として開業しました。<br /> 各企業のイベント、行事でも多数利用されています。',
  fullDescription: '孔雀の間、富士の間など、日本を代表する歴史ある会場がお別れの会、偲ぶ会でよく利用されます。孔雀の間は東と西に分けて、献花会場、懇談会場等に利用されることもあります。さらに参列が見込まれる場合は、隣接の南の間を控室等で利用いたします。<br /> 本館2F、3Fともに同フロアに多くの控室が設けられるので、来賓、一般、ご遺族、各種関係、主催者等全て区分することが可能です。',
  address: '東京都千代田区内幸町1-1-1',
  facilityDescription: '大小 全20宴会場　大宴会場「孔雀の間」「富士の間」最大収容人数3,000名',
  parking: '425台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/46/46_1.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/46/46_2.jpg',
  }, {
    area: '孔雀の間',
    description: '',
    imgPath: '/images/sougijou/46/46_3.jpg',
  }, {
    area: '孔雀の間(西)',
    description: '',
    imgPath: '/images/sougijou/46/46_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/46/46_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/46/46_6.jpg',
  }],
  access: '日比谷線・千代田線・都営三田線「日比谷駅」より徒歩3分。<br />都営三田線「内幸町駅」より徒歩3分。<br />日比谷線、丸の内線、銀座線「銀座駅」より徒歩5分。<br />有楽町線「有楽町駅」より徒歩7分。<br />銀座線・都営浅草線「新橋駅」7出口より徒歩9分。<br />JR線「有楽町駅」より徒歩5分、「新橋駅」より徒歩7分、「東京駅」よりタクシーにて5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/46/46_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '47',
  name: '東京ステーションホテル',
  nameHira: 'とうきょうすてーしょんほてる',
  description: '東京ステーションホテルは、東京駅開業翌年の1915年に開業しました。<br /> 大正・昭和・平成と受け継がれ、2003年には東京駅丸の内駅舎は国の重要文化財に指定されました。',
  fullDescription: '東京駅丸の内南口直結の利便性で、天候を気にすることなく遠方からお越しのお客様にも大変便利なロケーションです。<br /> 東京駅の喧噪を忘れるほどの静けさとヨーロピアンクラシックの洗練された空間、アースカラーを基調にした上品な設えと貸切感のある宴会場フロアが特徴です。<br /> お別れの会、偲ぶ会では、陽光を献花会場、鳳凰を懇談会場として利用することが多いです。<br /> また、陽光、桐は法要会場としてもよく利用されています。',
  address: '東京都千代田区丸の内1-9-1',
  facilityDescription: '大小 全3宴会場　大宴会場「鳳凰」最大収容人数200名',
  parking: '36台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/47/47_1.jpg',
  }, {
    area: '会食会場',
    description: '',
    imgPath: '/images/sougijou/47/47_2.jpg',
  }, {
    area: '鳳凰',
    description: '',
    imgPath: '/images/sougijou/47/47_3.jpg',
  }, {
    area: '陽光',
    description: '',
    imgPath: '/images/sougijou/47/47_4.jpg',
  }, {
    area: '駅舎外観',
    description: '',
    imgPath: '/images/sougijou/47/47_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/47/47_6.jpg',
  }],
  access: 'JR線「東京駅」丸の内南口改札より徒歩すぐ。丸ノ内線「東京駅」より徒歩3分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/47/47_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '48',
  name: '東京ドームホテル',
  nameHira: 'とうきょうどーむほてる',
  description: '東京ドームホテルは、東京都文京区後楽にあるホテルで、旧後楽園球場の跡地に2000年開業しました。<br /> ホテルが位置する水道橋、後楽園はJR、私鉄各線の鉄道網が重なるエリアで、東京や上野、池袋、新宿など主要ターミナル駅へのアクセスもしやすい、大変便利なロケーションです。',
  fullDescription: '東京ドームホテルには、大小18のバリエーション豊富な宴会場があります。42階にあるスカイバンケットは都内屈指の眺望で、東京タワー、新宿高層ビル群が一望できるロケーションです。立食1,000名規模の大人数を収容できる大宴会場「天空」は献花会場、懇談会場と分けて利用することにより、大規模なお別れの会、偲ぶ会に対応が可能です。<br /> B1Fの同フロアには、多くの控室が設けられるので、来賓、一般、ご遺族、各種関係、主催者等全て区分することも可能です。',
  address: '東京都文京区後楽1-3-61',
  facilityDescription: '大小 全18宴会場　大宴会場「天空」最大収容人数1,000名',
  parking: '283台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '受付',
    description: '',
    imgPath: '/images/sougijou/48/48_1.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/48/48_2.jpg',
  }, {
    area: '献花会場',
    description: '',
    imgPath: '/images/sougijou/48/48_3.jpg',
  }, {
    area: '懇談・会食',
    description: '',
    imgPath: '/images/sougijou/48/48_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/48/48_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/48/48_6.jpg',
  }],
  access: 'JR総武線「水道橋駅」東口より徒歩2分。<br />都営三田線「水道橋駅」A2出口より徒歩1分。<br />丸の内線・南北線「後楽園駅」2番出口より徒歩5分。<br />都営大江戸線「春日駅」6番出口より徒歩6分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/48/48_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '49',
  name: '東京プリンスホテル',
  nameHira: 'とうきょうぷりんすほてる',
  description: '東京プリンスホテルは東京都港区芝公園にあるホテルで、1964年の東京オリンピック開催に合わせて開業しました。<br /> 増上寺や芝公園、東京タワーに隣接したロケーションで「プリンスホテル」グランドの中でも代表格のホテルです。',
  fullDescription: '東京プリンスホテルには、大小24の個性豊かな宴会場があります。2Fにある東京プリンスホテルの主宴会場「鳳凰の間」は、マグノリアホールと合わせて利用することにより、式典会場、献花会場、懇談会場と分けた大規模なお別れの会、偲ぶ会に対応が可能です。<br /> 2Fの同フロアには、さらにサンフラワーホール、プロビデンスホールの大宴会場があるので、開会までの待合室としての利用も可能です。',
  address: '東京都港区芝公園3-3-1',
  facilityDescription: '大小 全24宴会場　大宴会場「鳳凰の間」最大収容人数2,000名',
  parking: '449台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/49/49_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/49/49_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/49/49_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/49/49_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/49/49_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/49/49_6.jpg',
  }],
  access: 'JR線・東京モノレール「浜松町駅」より徒歩10分。<br />都営三田線「御成門駅」A1出口より徒歩1分。<br />都営浅草線・大江戸線「大門駅」A6出口より徒歩7分。<br />日比谷線「神谷町駅」3番出口より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/49/49_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '50',
  name: '日本工業倶楽部',
  nameHira: 'にほんこうぎょうくらぶ',
  description: '日本工業倶楽部会館は、千代田区丸の内にある日本における数少ない本格的なセセッション様式の建物で、日本工業倶楽部創立後に建設が計画され、1920年に完成しました。<br /> 東京駅丸の内北口より徒歩2分という大変便利なロケーションです。',
  fullDescription: '大正9年に竣工した日本工業倶楽部会館（登録文化財）は、80数年にわたり、わが国経済界の様々なドラマの舞台となり、成長する日本経済の象徴として長くその歴史的な価値をとどめてきました。<br /> 平成15年、耐震性や安全性の面から、大規模な保存、建替工事を行い、新しい工業倶楽部会館が完成しました。<br /> 大正時代の面影を十分に残し、以前にもましてクラッシックな優雅さを誇る新会館は、大ホール、中ホール、大会堂を有し、200名～300名規模のお別れの会、偲ぶ会に対応が可能です。',
  address: '東京都千代田区丸の内1-4-6',
  facilityDescription: '大小 全3宴会場　大宴会場「大ホール」最大収容人数200～300名',
  parking: '34台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '大会堂',
    description: '',
    imgPath: '/images/sougijou/50/50_1.jpg',
  }, {
    area: '大ホール-1',
    description: '',
    imgPath: '/images/sougijou/50/50_2.jpg',
  }, {
    area: '大ホール-２',
    description: '',
    imgPath: '/images/sougijou/50/50_3.jpg',
  }, {
    area: '中ホール',
    description: '',
    imgPath: '/images/sougijou/50/50_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/50/50_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/50/50_6.jpg',
  }],
  access: 'JR線「東京駅」丸の内北口より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/50/50_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '51',
  name: 'ハイアットリージェンシー東京',
  nameHira: 'はいあっとりーじぇんしーとうきょう',
  description: 'ハイアット リージェンシー 東京は、新宿区西新宿にあるホテルです。<br /> 1980年に竣工した小田急センチュリービルに、日本初のハイアットホテル「ホテルセンチュリーハイアット」として開業しました。新宿の高層ビル群の中に有りながら、新宿中央公園に隣接し、四季折々の眺望があるホテルです。',
  fullDescription: 'ハイアットリージェンシー東京は、大小18のバリエーション豊富な会場があります。メイン会場のセンチュリールームとクリスタルルームを合わせると、式典会場、献花会場、懇談会場と分けた大規模なお別れの会、偲ぶ会に対応が可能です。<br /> B1Fの同フロアには多くの控室が設けられるので、来賓、一般、ご遺族、各種関係、主催者等全て区分することも可能です。<br /> 新宿駅からのアクセスの良さで、あらゆる規模、ご希望のお別れの会、偲ぶ会のご提案が可能なホテルです。',
  address: '東京都新宿区西新宿2-7-2',
  facilityDescription: '大小 全18宴会場　大宴会場「センチュリールーム」最大収容人数1,000名',
  parking: '415台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/51/51_1.jpg',
  }, {
    area: 'センチュリールーム-1',
    description: '',
    imgPath: '/images/sougijou/51/51_2.jpg',
  }, {
    area: 'センチュリールーム-2',
    description: '',
    imgPath: '/images/sougijou/51/51_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/51/51_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/51/51_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/51/51_6.jpg',
  }],
  access: 'JR線「新宿駅」西口より徒歩9分。都営大江戸線「都庁前駅」A7出口C4連絡通路（6:00～23:00）経由より徒歩1分。丸ノ内線「西新宿駅」より徒歩4分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/51/51_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '52',
  name: '八芳園',
  nameHira: 'はっぽうえん',
  description: '八芳園は、東京都港区白金台に所在する、お別れの会、偲ぶ会の会場として利用できる総合集宴会施設です。<br /> 12,000坪の敷地にある回遊式庭園は、四季折々のを美しい庭園をかたちづくっています。',
  fullDescription: '中庭に続く主宴会場「ジュール」、専用テラスから庭園に行くことができる「ニュイ」のあるガーデンフロアと名付けられた1Ｆは、庭園との一体感を感じられる特別な空間です。献花会場、懇談会場と区分して利用すれば、大規模なお別れの会、偲ぶ会としての利用が可能です。<br /> また、各フロアにある個性ある宴会場は、規模、ご意向に合わせた法事、偲ぶ会でご利用いただけます。',
  address: '東京都港区白金台1-1-1',
  facilityDescription: '大小 全13宴会場　大宴会場「ジュール」最大収容人数700名',
  parking: '150台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '会場',
    description: '',
    imgPath: '/images/sougijou/52/52_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/52/52_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/52/52_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/52/52_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/52/52_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/52/52_6.jpg',
  }],
  access: '南北線・都営三田線「白金台駅」より徒歩1分。JR線「目黒駅」よりタクシーにて5分。JR線「品川駅」よりタクシーにて5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/52/52_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '53',
  name: 'パレスホテル立川',
  nameHira: 'ぱれすほてるたちかわ',
  description: 'パレスホテル立川は、東京都立川市の再開発エリア「ファーレ立川」に位置するホテルです。<br /> 周辺地域密着型のコミュニティホテルとして、地産地消の取組みを推進し地域と協和しています。',
  fullDescription: '東京多摩地区最大規模の大宴会場「ローズルーム」をはじめ、規模・ご希望に合わせご利用いただける13の宴会場があります。<br /> ローズルームは、式典会場、献花会場、懇談会場の3分割での利用が可能で、格式あるお別れの会、偲ぶ会に対応が可能です。<br /> また、各フロアにある個性ある宴会場は、規模、ご意向に合わせた法事、偲ぶ会でご利用いただけます。',
  address: '東京都立川市曙町2-40-15',
  facilityDescription: '大小 全13宴会場　大宴会場「ローズルーム」最大収容人数800～900名',
  parking: '80台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/53/53_1.jpg',
  }, {
    area: '懇談・会食',
    description: '',
    imgPath: '/images/sougijou/53/53_2.jpg',
  }, {
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/53/53_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/53/53_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/53/53_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/53/53_6.jpg',
  }],
  access: '多摩モノレール「立川北駅」より徒歩すぐ。JR線「立川駅」北口より徒歩2分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/53/53_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '54',
  name: 'パレスホテル東京',
  nameHira: 'ぱれすほてるとうきょう',
  description: 'パレスホテル東京は、東京都千代田区丸の内にあるパレスホテルチェーンの旗艦ホテルです。<br /> 皇居に隣接する建物として、周辺環境の調和と一流ホテルとしての品格にこだわった外観のホテルです。地下鉄大手町駅、地下通路直結の利便性の高いロケーションです。',
  fullDescription: 'パレスホテル東京は、全8室の大・中・小宴会場を有しており、2Fメイン宴会場の「葵」は、大規模なお別れの会、偲ぶ会が可能です。<br /> 一面が大窓となっており、目の前には、皇居周辺の豊かな緑と水の眺望が広がります。<br /> 最新の映像・照明・音響システムによる様々な演出は、お別れの会をさらに格調高いものにしてくれるでしょう。',
  address: '東京都千代田区丸の内1-1-1',
  facilityDescription: '大小 全8宴会場　大宴会場「葵」最大収容人数1,500名',
  parking: '350台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '受付',
    description: '',
    imgPath: '/images/sougijou/54/54_1.jpg',
  }, {
    area: '祭壇-1',
    description: '',
    imgPath: '/images/sougijou/54/54_2.jpg',
  }, {
    area: '祭壇-2',
    description: '',
    imgPath: '/images/sougijou/54/54_3.jpg',
  }, {
    area: '懇談・会食',
    description: '',
    imgPath: '/images/sougijou/54/54_4.jpg',
  }, {
    area: '葵の間',
    description: '',
    imgPath: '/images/sougijou/54/54_5.jpg',
  }, {
    area: '控室（橘）',
    description: '',
    imgPath: '/images/sougijou/54/54_6.jpg',
  }, {
    area: '山吹前室',
    description: '',
    imgPath: '/images/sougijou/54/54_7.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/54/54_8.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/54/54_9.jpg',
  }, {
    area: '眺望',
    description: '',
    imgPath: '/images/sougijou/54/54_10.jpg',
  }],
  access: '千代田線・半蔵門線・丸ノ内線・東西線・都営三田線「大手町駅」C13b出口より徒歩すぐ。',
  caseCategory: 'owakarenokai',
  caseId: '001',
  imagePath: '/images/sougijou/54/54_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '55',
  name: 'ヒルトン東京',
  nameHira: 'ひるとんとうきょう',
  description: 'ヒルトン東京は、東京都新宿区西新宿6丁目にある高級ホテルです。西新宿の高層ビル群を望むロケーションで、新宿駅徒歩10分、地下鉄西新宿駅 地下通路直結の最高のアクセスを誇ります。',
  fullDescription: 'ヒルトン東京には、大小20の個性豊かな宴会場があります。4Fにあるヒルトン東京を代表する主宴会場「菊」は、最大4分割にして利用することにより、式典会場、献花会場、懇談会場と分けた大規模なお別れの会、偲ぶ会に対応が可能です。<br /> また、各フロアにある個性ある宴会場は、規模、ご意向に合わせた法事、偲ぶ会でご利用いただけます。',
  address: '東京都新宿区西新宿6-6-2',
  facilityDescription: '大小 全20宴会場　大宴会場「菊」最大収容人数900名',
  parking: '280台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/55/55_1.jpg',
  }, {
    area: '大宴会場',
    description: '',
    imgPath: '/images/sougijou/55/55_2.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/55/55_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/55/55_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/55/55_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/55/55_6.jpg',
  }],
  access: 'JR線「新宿駅」より徒歩10分、タクシーにて5分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/55/55_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '56',
  name: 'ヒルトン東京お台場',
  nameHira: 'ひるとんとうきょうおだいば',
  description: 'ヒルトン東京お台場は、東京都港区台場に所在するシティホテルです。<br /> 東京のウォーターフロントに位置しながら、都心まで約20分という好アクセスでビジネスや観光にも最適なロケーションにあります。',
  fullDescription: 'ヒルトン東京お台場には、大小12の個性豊かな宴会場があります。1Fにあるヒルトン東京お台場を代表する主宴会場「ペガサス」は、天井高8メートルを誇り、最大3分割にして利用することにより、式典会場、献花会場、懇談会場と分け、最大1,200規模のお別れの会、偲ぶ会に対応が可能です。<br /> また、海に面したテラス付き宴会場では東京湾、レインボーブリッジ、東京タワーを一望でき、規模、ご意向に合わせた法事、偲ぶ会でご利用いただけます。',
  address: '東京都港区台場1-9-1',
  facilityDescription: '大小 全12宴会場　大宴会場「ペガサス」最大収容人数1,600名',
  parking: '300台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/56/56_1.jpg',
  }, {
    area: '全景',
    description: '',
    imgPath: '/images/sougijou/56/56_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/56/56_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/56/56_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/56/56_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/56/56_6.jpg',
  }],
  access: 'ゆりかもめ「台場駅」より徒歩すぐ。りんかい線「東京テレポート駅」より徒歩10分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/56/56_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '57',
  name: 'オークラ東京',
  nameHira: 'おーくらとうきょう',
  description: 'オークラ東京はホテル御三家のひとつで、港区にある日本を代表するホテルです。<br /> 2019年9月「The Okura Tokyo」となり、「オークラ プレステージタワー」「オークラ ヘリテージウイング」の2つのブランドを持つホテルへ生まれ変わりました。',
  fullDescription: 'The Okura Tokyoには、大小19のコンセプト・規模の異なる宴会場があります。オークラを象徴する大宴会場「平安の間」は、隣接するホワイエ、「曙の間」との一体利用で3,000㎡、都内でも最大規模の宴会場となります。<br /> また、各フロアにある装飾、趣向を凝らした個性ある宴会場は、規模、ご意向に合わせ法事、偲ぶ会などでご利用いただけます。',
  address: '東京都港区虎ノ門2-10-4',
  facilityDescription: '大小 全19宴会場　大宴会場「平安の間」最大収容人数2,000名',
  parking: '329台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/57/57_1.jpg',
  }, {
    area: '懇談会場-1',
    description: '',
    imgPath: '/images/sougijou/57/57_2.jpg',
  }, {
    area: '懇談会場-2',
    description: '',
    imgPath: '/images/sougijou/57/57_3.jpg',
  }, {
    area: 'メモリアルコーナー',
    description: '',
    imgPath: '/images/sougijou/57/57_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/57/57_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/57/57_6.jpg',
  }],
  access: '[東京メトロ 日比谷線] 虎ノ門ヒルズ駅 出口A2より徒歩5分(宴会場入口まで)<br />[東京メトロ 銀座線] 虎ノ門駅 出口3より徒歩10分<br />[東京メトロ 銀座線・南北線] 溜池山王駅 出口14より徒歩10分<br /><br />■東京駅より><br />＜JR山手線＞東京駅 → ＜丸ノ内線＞霞ヶ関駅 → ＜日比谷線＞虎ノ門ヒルズ駅 　約16分<br />＜タクシー＞　約15分<br /><br />■羽田空港より<br />＜東京モノレール＞羽田空港第１ビル → ＜JR京浜東北線＞浜松町駅 →＜タクシー利用＞ 約35分<br />＜タクシー＞　約30分<br />＜リムジンバス＞　約60分<br /><br />■成田空港より<br />＜成田エクスプレス＞成田空港駅 → ＜山手線＞東京駅 → ＜丸ノ内線＞霞ヶ関駅 → ＜日比谷線＞ 虎ノ門ヒルズ駅　約75分<br />＜タクシー＞　約70分<br />＜リムジンバス＞　約90分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/57/57_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '58',
  name: 'ホテル雅叙園東京',
  nameHira: 'ほてるがじょえんとうきょう',
  description: 'ホテル雅叙園東京は、東京都目黒区にある、結婚式場・ホテル・レストランなどの複合施設です。<br /> 歴史ある老舗の結婚式場「目黒雅叙園」をよりサービス向上するために2017年にリニューアルオープンしました。<br /> 90年以上の伝統を受け継ぎ、2,500点もの日本画や美術工芸品に彩られた唯一無二のミュージアムホテルです。',
  fullDescription: 'ホテル雅叙園東京は、日本美の粋を尽くした和室宴会場をはじめとした23の宴会施設、そして東京都指定有形文化財の「百段階段」を有しています。<br /> 2Fにあるホテル雅叙園東京を代表する和モダンな大宴会場「舞扇」は、2つの空間に分割にして利用することにより、式典・献花会場、懇談会場と分けた大規模なお別れの会、偲ぶ会に対応が可能です。<br /> また、趣向を凝らした各宴会場は、規模、ご意向に合わせたお別れの会、偲ぶ会、法事でご利用いただけます。',
  address: '東京都目黒区下目黒1-8-1',
  facilityDescription: '大小 全23宴会場　大宴会場「舞扇」最大収容人数1,000名',
  parking: '160台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '花苑',
    description: '',
    imgPath: '/images/sougijou/58/58_1.jpg',
  }, {
    area: '回廊',
    description: '',
    imgPath: '/images/sougijou/58/58_2.jpg',
  }, {
    area: '舞扇',
    description: '',
    imgPath: '/images/sougijou/58/58_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/58/58_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/58/58_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/58/58_6.jpg',
  }],
  access: '目黒駅（JR山手線西口、東急目黒線、地下鉄南北線・三田線）より行人坂を下って徒歩3分。権之助坂を下って徒歩5分。 （行人坂はに沿ってお進みください）<br /><br />＜主要な駅から目黒駅までの所要時間＞<br />　　内周り：渋谷5分、新宿11分、池袋20分<br />　　外回り：品川7分、浜松町12分、東京20分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/58/58_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '59',
  name: 'ホテルニューオータニ',
  nameHira: 'ほてるにゅーおーたに',
  description: 'ホテルニューオータニはホテル御三家のひとつで、千代田区にある日本を代表するホテルです。<br /> 1964年の東京オリンピック開催に合わせ開業しました。<br /> ザ・メイン、ガーデンタワー、ガーデンコートの3棟で成り立つホテルです。',
  fullDescription: 'ホテルニューオータニには、大小35のコンセプト・規模の異なる宴会場があります。大宴会場「鶴の間」、「芙蓉の間」は国際都市TOKYOを代表する、第一級のグランドバンケットルームとして、大規模なお別れの会、偲ぶ会でご利用いただけます。<br /> また、数多くの装飾、趣向を凝らした個性ある宴会場は、規模、ご希望に合わせお別れの会、偲ぶ会、法事などでご利用いただけます。',
  address: '東京都千代田区紀尾井町4-1',
  facilityDescription: '大小 全35宴会場　大宴会場「鶴の間」「芙蓉の間」最大収容人数2,500名',
  parking: '760台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '祭壇',
    description: '',
    imgPath: '/images/sougijou/59/59_1.jpg',
  }, {
    area: '鶴の間',
    description: '',
    imgPath: '/images/sougijou/59/59_2.jpg',
  }, {
    area: '懇談会場',
    description: '',
    imgPath: '/images/sougijou/59/59_3.jpg',
  }, {
    area: '入口',
    description: '',
    imgPath: '/images/sougijou/59/59_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/59/59_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/59/59_6.jpg',
  }],
  access: '東京メトロ銀座線・丸ノ内線「赤坂見附駅」D紀尾井町口より徒歩3分。<br /><br />東京メトロ半蔵門線・南北線「永田町駅」7番口より徒歩3分。<br /><br />東京メトロ有楽町線「麹町駅」2番口より徒歩6分。<br /><br />JR中央線・総武線、東京メトロ丸ノ内線・南北線「四ツ谷駅」麹町口・赤坂口より徒歩8分。',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/59/59_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '60',
  name: '明治記念館',
  nameHira: 'めいじきねんかん',
  description: '明治記念館は、東京都港区に所在します。明治14年、当時の赤坂仮皇居の御会食所(日本で初めての 迎賓館)として今の迎賓館のある場所に建てられた明治記念館本館は、令和2年に歴史的・建築的価値が認められ東京都指定有形文化財に指定されました。歴史を経て守られてきたものに静かに包まれる贅沢な時間をご提供いたします。',
  fullDescription: '明治記念館は豊かな緑に包まれた明治神宮外苑の一角、都心であることを忘れてしまいそうな場所にごさいます。館内には、プライベートテラス付きの会場や、庭園を臨める会場などさまざまな趣向を凝らした宴会場がございます。大宴会場「富士」は、2つの部屋に分けて使用することもでき、式典・献花会場、懇親会場と分けて大規模なお別れの会・偲ぶ会でのご利用も可能です。その他にも、規模やご希望に合わせた会場で、お別れの会・偲ぶ会・法事等のご利用をいただけます。',
  address: '東京都港区元赤坂2-2-23',
  facilityDescription: '大小 全15宴会場　大宴会場「富士」最大収容人数800名（立食）',
  parking: '160台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '正門',
    description: '',
    imgPath: '/images/sougijou/60/60_1.jpg',
  }, {
    area: 'エントランス',
    description: '',
    imgPath: '/images/sougijou/60/60_2.jpg',
  }, {
    area: '庭園',
    description: '',
    imgPath: '/images/sougijou/60/60_3.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/60/60_4.jpg',
  }, {
    area: '金鶏(明治記念館本館)',
    description: '',
    imgPath: '/images/sougijou/60/60_5.jpg',
  }, {
    area: '富士',
    description: '',
    imgPath: '/images/sougijou/60/60_6.jpg',
  }],
  access: '最寄り駅は下記3駅になります。<br /><br />JR中央・総武線【信濃町駅】下車徒歩3分<br /><br />地下鉄 銀座線・半蔵門線・大江戸線【青山一丁目駅】下車（2番出口）徒歩6分<br /><br />地下鉄 大江戸線　【国立競技場駅】下車（A1出口）徒歩6分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/60/60_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '61',
  name: 'ロイヤルパークホテル',
  nameHira: 'ろいやるぱーくほてる',
  description: 'ロイヤルパークホテルは、東京都中央区日本橋に所在する、三菱地所グループが展開するホテルチェーン「ロイヤルパークホテルズ」のフラグシップホテルです。<br /> 東京メトロ「水天宮前駅」直結の利便性の高いロケーションです。',
  fullDescription: 'ロイヤルパークホテルには、大小11のコンセプト・規模の異なる宴会場があります。格調高いインテリアと美しいシャンデリアが目を惹く大宴会場「ロイヤルホール」は会場前のホワイエを全室として利用すると、600名～700名規模のお別れの会でご利用いただけます。<br /> また、会場は3分割にすることができ、規模・形式に応じた提案が可能です。',
  address: '東京都中央区日本橋蛎殻町2-1-1',
  facilityDescription: '大小 全11宴会場　大宴会場「ロイヤルホール」最大収容人数1,000名',
  parking: '176台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'ロイヤルホール',
    description: '',
    imgPath: '/images/sougijou/61/61_1.jpg',
  }, {
    area: 'ロイヤルホール　ホワイエ',
    description: '',
    imgPath: '/images/sougijou/61/61_2.jpg',
  }, {
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/61/61_3.jpg',
  }, {
    area: '有明',
    description: '',
    imgPath: '/images/sougijou/61/61_4.jpg',
  }, {
    area: '東雲',
    description: '',
    imgPath: '/images/sougijou/61/61_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/61/61_6.jpg',
  }],
  access: '東京メトロ半蔵門線「水天宮前駅」に直結(4番出口)<br /><br />東京メトロ日比谷線「人形町駅」より徒歩5分(A2出口)<br /><br />都営浅草線「人形町駅」より徒歩8分(A3出口)',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/61/61_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '62',
  name: '横浜ベイシェラトン ホテル＆タワーズ',
  nameHira: 'よこはまべいしぇらとんほてるあんどたわーず',
  description: '横浜ベイシェラトン ホテル&タワーズとは、横浜市西区にある高級ホテルです。1998年、横浜駅西口の目の前に28階建て高層ホテルとしてオープンしました。',
  fullDescription: '横浜駅やその他の交通機関にすぐにアクセスできる横浜ベイシェラトン ホテル＆タワーズは、にぎやかで慌ただしい都会にありながらも静かな安らぎのひとときをお過ごしいただける快適な横浜のシティホテルです。<br /> 圧倒的な開放感を誇る日輪は、1,000名規模の催しなどにも最適です。<br /> 可動式の間仕切により、分割してのご利用もいただけます。',
  address: '神奈川県横浜市西区北幸1-3-23',
  facilityDescription: '大小 全5宴会場　大宴会場「日輪」最大収容人数1,000名',
  parking: '230台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '日輪',
    description: '',
    imgPath: '/images/sougijou/62/62_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/62/62_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/62/62_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/62/62_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/62/62_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/62/62_6.jpg',
  }],
  access: '『横浜駅西口』 より徒歩1分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/62/62_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '63',
  name: '川越プリンスホテル',
  nameHira: 'かわごえぷりんすほてる',
  description: '川越プリンスホテルは埼玉県唯一のプリンスホテルであると<br /> 共に昔懐かしい面影を残す町小江戸川越であり、都心からで<br /> も特急小江戸号でゆったりと座って43分と、観光にゴルフに<br /> ビジネスの拠点としても大変便利なホテルです。',
  fullDescription: '川越プリンスホテルは1,200名様までご利用いただける主宴会場プリンスホールをはじめ合計7室の宴会場や神式、キリスト教式の結婚式場<br /> からバラエティー豊かな8つのレストラン・バー、そして趣ある4室の和室をあわせて、ごゆっくりおくつろぎいただける110室の客室など<br /> ご宿泊・ご婚礼・ご宴会・セミナーにと充実したホテルライフをお楽しみいただけます。',
  address: '埼玉県川越市新富町1-22',
  facilityDescription: '主宴会場｢プリンスホール｣最大収容人数1,200名大小全110室の宿泊施設',
  parking: '330台',
  fee: '',
  remarks: '',
  facilityList: [],
  access: '西武新宿線 本川越駅        直結 (天候に関係なくまた荷物等がある場合など大変便利です。)<br /><br />東武東上線 川越市駅        徒歩約5分<br /><br />JR線、東武東上線 川越駅        徒歩約10分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/63/63_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '64',
  name: 'パレスホテル大宮',
  nameHira: 'ぱれすほてるおおみや',
  description: 'パレスホテル大宮は北関東随一の経済と交通の要所大宮駅<br /> 西口ソニックシティ内に位置する本格的な都市型多目的<br /> ホテルです。',
  fullDescription: 'パレスホテル大宮には大小19のコンセプト・規模のことなる宴会場があります。大宴会場「ローズルーム」は華やかな中にも落ち着きを備えたモダンクラシックな空間を、最大で3分割にすることが可能です。ご希望に合わせ、式典会場、献花会場、懇談会場に分けたお別れの会、偲ぶ会を行うことが可能です。',
  address: '埼玉県さいたま市大宮区桜木町1-7-5',
  facilityDescription: '大小　全３宴会場　大宴会場最大収容人数1,500名',
  parking: 'ソニックシティ地下駐車場　近隣提携駐車場利用サービス有',
  fee: '',
  remarks: '',
  facilityList: [{
    area: 'ロビー',
    description: '',
    imgPath: '/images/sougijou/64/64_1.jpg',
  }, {
    area: 'ローズルーム（献花会場）',
    description: '',
    imgPath: '/images/sougijou/64/64_2.jpg',
  }, {
    area: 'ローズルーム（懇談・会食会場）',
    description: '',
    imgPath: '/images/sougijou/64/64_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/64/64_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/64/64_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/64/64_6.jpg',
  }],
  access: '大宮駅から徒歩3分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/64/64_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '65',
  name: '三井ガーデンホテル千葉',
  nameHira: 'みついがーでんほてるちば',
  description: '三井ガーデンホテル千葉は、千葉県千葉市中央区にある千葉中央ツインビル1号館の上層階部に所在するホテルです。',
  fullDescription: '三井ガーデンホテル千葉は、政府登録国際観光旅館に登録されているホテルです。<br /> JR東日本・千葉都市モノレールの千葉駅からは成田国際空港方面（成田空港駅・空港第2ビル駅）や東京都の都心方面（東京駅など）に直接アクセスできるため交通至便な場所に位置しています。<br /> 大人数での催しなどに最適な会場や、少人数でのご会食の会場など、ご要望に合わせたさまざまなタイプのお部屋をご用意しております。',
  address: '千葉県千葉市中央区中央1-11-1',
  facilityDescription: '大小 全11宴会場　大宴会場「平安」最大収容人数600名',
  parking: '146台',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '平安の間',
    description: '',
    imgPath: '/images/sougijou/65/65_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/65/65_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/65/65_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/65/65_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/65/65_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/65/65_6.jpg',
  }],
  access: '・JR「千葉」駅東口より徒歩7分<br />・京成千葉線「千葉中央」駅より徒歩7分<br />・千葉都市モノレール1号線「葭川公園」駅より徒歩2分',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/65/65_main.jpg',
  hasMorgue: false,
  ceremore: false,
},];

export const OTHERS: Facility[] = [{
  id: '66',
  name: '泉ガーデンギャラリー',
  nameHira: 'いずみがーでんぎゃらりー',
  description: '泉ガーデンギャラリーは、三井住友不動産ベルサールが運営するイベントホール、貸会議室等の施設です。経年数にかかわらず建物の品質を維持する努力が行われており住友不動産が管理するビル内の高品質な空間となっております。',
  fullDescription: '泉ガーデンギャラリーは100名から700名規模の収容施設です。小規模なお別れの会から中規模なお別れの会までご利用いただけます。周辺にはハイエンドホテルや高級レジデンスが軒を連ねてますが、泉ガーデンギャラリーは都心とは思えない緑豊かな立地です。VIPの来場に配慮した動線で専用駐車場からバックヤードにある控室まで、参列者と交わることなくご案内が可能です。交通アクセスも良く、六本木一丁目駅の北改札より徒歩3分で、会葬者にとっても利便性の高い会場です。',
  address: '東京都港区 六本木1-5-2',
  facilityDescription: '',
  parking: '',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '泉ガーデンギャラリー　会場',
    description: '',
    imgPath: '/images/sougijou/66/66_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/66/66_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/66/66_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/66/66_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/66/66_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/66/66_6.jpg',
  }],
  access: '「六本木一丁目駅」北改札徒歩3分（南北線）<br />「神谷町駅」2番出口徒歩7分（日比谷線）<br />「溜池山王駅」13番出口徒歩7分（銀座線･南北線）<br />「六本木駅」5番出口徒歩11分（大江戸線・日比谷線）',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/66/66_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '67',
  name: 'ベルサール新宿グランド',
  nameHira: 'べるさーるしんじゅくぐらんど',
  description: 'ベルサール新宿グランドは、三井住友不動産ベルサールが運営するイベントホール、貸会議室等の施設です。経年数にかかわらず建物の品質を維持する努力が行われており住友不動産が管理するビル内の高品質な空間となっております。',
  fullDescription: 'ベルサール新宿グランドは天井高6ｍの整形無柱空間により1,400名を超える会葬者を収容できる大型ホールです。受付で使用するロビーとホールを合わせると約2,000㎡の広々とした空間です。専用エントランスからホールまでのアプローチはフラットな設計で雨天時もご安心いただけます。交通アクセスも良く、西新宿駅1番出口より徒歩4分で、会葬者にとっても利便性の高い会場です。',
  address: '東京都新宿区西新宿8-17-3',
  facilityDescription: '',
  parking: '',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '新宿グランド　ロビー',
    description: '',
    imgPath: '/images/sougijou/67/67_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/67/67_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/67/67_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/67/67_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/67/67_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/67/67_6.jpg',
  }],
  access: '「西新宿駅」1番出口徒歩4分（丸ノ内線）<br />「都庁前駅」A5出口徒歩8分（大江戸線）<br />「新宿駅」西口徒歩14分（JR線・小田急線・京王線）<br />',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/67/67_main.jpg',
  hasMorgue: false,
  ceremore: false,
},
{
  id: '68',
  name: 'ベルサール高田馬場',
  nameHira: 'べるさーるたかだのばば',
  description: 'ベルサール高田馬場は、三井住友不動産ベルサールが運営するイベントホール、貸会議室等の施設です。経年数にかかわらず建物の品質を維持する努力が行われており住友不動産が管理するビル内の高品質な空間となっております。',
  fullDescription: 'ベルサール高田馬場は戸山公園に隣接し、また周辺には大学や各種学校の多い落ち着いた立地でお別れの会にも適しております。2,000名を超える大規模なお別れの会にも対応できるホール。VIPの来場に配慮した動線で専用駐車場からバックヤードにある控室まで、参列者と交わることなくご案内が可能です。交通アクセスも良く、高田馬場駅戸山口より徒歩4分で、会葬者にとっても利便性の高い会場です。',
  address: '東京都新宿区大久保3-8-2',
  facilityDescription: '',
  parking: '',
  fee: '',
  remarks: '',
  facilityList: [{
    area: '高田馬場　会場',
    description: '',
    imgPath: '/images/sougijou/68/68_1.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/68/68_2.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/68/68_3.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/68/68_4.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/68/68_5.jpg',
  }, {
    area: '',
    description: '',
    imgPath: '/images/sougijou/68/68_6.jpg',
  }],
  access: '「高田馬場駅」戸山口徒歩4分（JR線）<br />「高田馬場駅」戸山口徒歩5分（西武新宿線）<br />「高田馬場駅」3番出口徒歩6分（東西線）<br />「西早稲田駅」2番出口徒歩7分（副都心線）',
  caseCategory: '',
  caseId: '',
  imagePath: '/images/sougijou/68/68_main.jpg',
  hasMorgue: false,
  ceremore: false,
},];